[functions.generate-pin]
verify_jwt = false

[functions.oauth]
verify_jwt = false

[functions.fc-last-conversation]
verify_jwt = false

[functions.fc-update-conversation]
verify_jwt = false

[functions.fc-ingest-conversations]
verify_jwt = false

[functions.advise-sync]
verify_jwt = false

[functions.datajud-search]
verify_jwt = false

[functions.processo-sync]
verify_jwt = false

[functions.publicacoes-prazos]
verify_jwt = false

[functions.publicacoes-audiencias]
verify_jwt = false

[functions.dotobot-slack]
verify_jwt = false

[functions.publicacoes-freshsales]
verify_jwt = false

[functions.datajud-andamentos-sync]
verify_jwt = false

[functions.publicacoes-partes]
verify_jwt = false

[functions.orchestrator-engine]
verify_jwt = false

[functions.datajud-worker]
verify_jwt = false
