export default function buildMarketAdsControllerValue({
  state,
  derived,
  forms,
  creativeActions,
  crudActions,
  integrationActions,
  load,
}) {
  return {
    state,
    meta: state.meta,
    data: derived.data,
    campaigns: derived.campaigns,
    adItems: derived.adItems,
    persistedTemplates: derived.persistedTemplates,
    preview: derived.preview,
    complianceResult: derived.complianceResult,
    strategyQueue: derived.strategyQueue,
    optimizationRecommendations: derived.optimizationRecommendations,
    funnelRecentLeads: derived.funnelRecentLeads,
    leadForecastQueue: derived.leadForecastQueue,
    generator: forms.generator,
    setGenerator: forms.setGenerator,
    previewState: creativeActions.previewState,
    draftState: creativeActions.draftState,
    campaignForm: forms.campaignForm,
    setCampaignForm: forms.setCampaignForm,
    campaignState: crudActions.campaignState,
    editingCampaignId: forms.editingCampaignId,
    landingState: crudActions.landingState,
    integrationState: integrationActions.integrationState,
    remoteSyncState: integrationActions.remoteSyncState,
    remoteImportState: integrationActions.remoteImportState,
    remoteAdSyncState: integrationActions.remoteAdSyncState,
    remoteAdImportState: integrationActions.remoteAdImportState,
    optimizationState: integrationActions.optimizationState,
    applyOptimizationState: integrationActions.applyOptimizationState,
    templateState: creativeActions.templateState,
    attributionForm: forms.attributionForm,
    setAttributionForm: forms.setAttributionForm,
    attributionState: creativeActions.attributionState,
    adForm: forms.adForm,
    setAdForm: forms.setAdForm,
    adState: crudActions.adState,
    editingAdId: forms.editingAdId,
    abForm: forms.abForm,
    setAbForm: forms.setAbForm,
    abState: crudActions.abState,
    editingAbId: forms.editingAbId,
    complianceInput: forms.complianceInput,
    setComplianceInput: forms.setComplianceInput,
    complianceState: creativeActions.complianceState,
    load,
    inspectIntegrations: integrationActions.inspectIntegrations,
    syncRemoteCampaigns: integrationActions.syncRemoteCampaigns,
    importRemoteCampaigns: integrationActions.importRemoteCampaigns,
    syncRemoteAds: integrationActions.syncRemoteAds,
    importRemoteAds: integrationActions.importRemoteAds,
    saveCampaign: crudActions.saveCampaign,
    recommendLanding: crudActions.recommendLanding,
    resetCampaignForm: forms.resetCampaignForm,
    applyRecommendedLanding: crudActions.applyRecommendedLanding,
    saveAdItem: crudActions.saveAdItem,
    resetAdForm: forms.resetAdForm,
    saveAbTest: crudActions.saveAbTest,
    resetAbForm: forms.resetAbForm,
    generatePreview: creativeActions.generatePreview,
    saveDraft: creativeActions.saveDraft,
    validateCompliance: creativeActions.validateCompliance,
    generateOptimizations: integrationActions.generateOptimizations,
    applyOptimizations: integrationActions.applyOptimizations,
    beginEditAbTest: forms.beginEditAbTest,
    beginEditCampaign: forms.beginEditCampaign,
    generateFromWinner: creativeActions.generateFromWinner,
    saveTemplate: creativeActions.saveTemplate,
    toggleTemplateFavorite: creativeActions.toggleTemplateFavorite,
    toggleTemplateVisibility: creativeActions.toggleTemplateVisibility,
    toggleTemplateEditScope: creativeActions.toggleTemplateEditScope,
    generateFromTemplate: creativeActions.generateFromTemplate,
    saveAttribution: creativeActions.saveAttribution,
    beginEditAd: forms.beginEditAd,
  };
}
