import InternoConsoleHistoryListCard from "./InternoConsoleHistoryListCard";
import InternoConsoleHistorySnapshotCard from "./InternoConsoleHistorySnapshotCard";

export default function InternoConsoleHistoryTab(props) {
  const { aiTaskHistory, contactsHistory, dotobotHistory, handleCopyAiTaskHistory, handleCopyContactsHistory, handleCopyDotobotHistory, handleCopyProcessHistory, handleCopyPublicacoesHistory, isLightTheme, processosLocalHistory, processosRemoteHistory, publicacoesLocalHistory, publicacoesRemoteHistory } = props;
  const infoClass = isLightTheme ? "border-[#D7DEE8] bg-[#F7F9FC] text-[#6B7C88]" : "border-[#1E2E29] bg-[rgba(10,12,11,0.6)] text-[#9BAEA8]";
  return <div className="space-y-3">
    <div className={`rounded-xl border p-3 text-[11px] ${infoClass}`}>Historicos e snapshots operacionais separados por modulo.</div>
    <InternoConsoleHistoryListCard copyLabel="Copiar historico" emptyLocalText="Sem historico local registrado." emptyRemoteText="Sem historico remoto disponivel." handleCopy={handleCopyProcessHistory} isLightTheme={isLightTheme} localEntries={processosLocalHistory} remoteEntries={processosRemoteHistory} subtitle="Consolidado do modulo Processos no console." title="Historico de execucao" />
    <InternoConsoleHistoryListCard copyLabel="Copiar historico" emptyLocalText="Sem historico local registrado." emptyRemoteText="Sem historico remoto disponivel." handleCopy={handleCopyPublicacoesHistory} isLightTheme={isLightTheme} localEntries={publicacoesLocalHistory} remoteEntries={publicacoesRemoteHistory} subtitle="Consolidado do modulo Publicacoes no console." title="Historico de publicacoes" />
    <InternoConsoleHistorySnapshotCard emptyText="Sem snapshot de Contacts." handleCopy={handleCopyContactsHistory} history={contactsHistory} isLightTheme={isLightTheme} primaryLines={{ label: "Contato em foco", value: contactsHistory?.selectedContact?.name || "nenhum", subtitle: "Snapshot de qualidade da base, bulk actions e persistencia do modulo.", details: [`total ${contactsHistory?.overview?.total || 0} · duplicados ${contactsHistory?.overview?.duplicados || 0} · partes sem contato ${contactsHistory?.overview?.partesSemContato || 0}`, `sync ${contactsHistory?.settings?.syncLimit || 0} · reconcile ${contactsHistory?.settings?.reconcileLimit || 0} · pendentes selecionadas ${contactsHistory?.partesPendentes?.selected || 0} · vinculadas selecionadas ${contactsHistory?.partesVinculadas?.selected || 0}`, ...(contactsHistory?.actionState?.preview ? [`Ultima acao: ${contactsHistory.actionState.preview}`] : []), ...(contactsHistory?.actionState?.error ? [`Erro: ${contactsHistory.actionState.error}`] : [])] }} title="Contacts" />
    <InternoConsoleHistorySnapshotCard emptyText="Sem snapshot do Dotobot." handleCopy={handleCopyDotobotHistory} history={dotobotHistory} isLightTheme={isLightTheme} primaryLines={{ label: "Estado", value: dotobotHistory?.uiState || "idle", subtitle: "Snapshot do copilot, chat e task runs locais.", details: [`modo ${dotobotHistory?.mode || "n/a"} · provider ${dotobotHistory?.provider || "n/a"} · conversas ${dotobotHistory?.conversationCount || 0}`, ...(dotobotHistory?.activeTask ? [`Task ativa: ${dotobotHistory.activeTask.query || dotobotHistory.activeTask.id}`] : []), ...(dotobotHistory?.error ? [`Erro: ${dotobotHistory.error}`] : [])] }} title="Dotobot" />
    <InternoConsoleHistorySnapshotCard emptyText="Sem snapshot do AI Task." handleCopy={handleCopyAiTaskHistory} history={aiTaskHistory} isLightTheme={isLightTheme} primaryLines={{ label: "Automacao", value: aiTaskHistory?.automation || "idle", subtitle: "Run ativa, trilha de logs e contexto persistido do orquestrador.", details: [`modo ${aiTaskHistory?.mode || "n/a"} · provider ${aiTaskHistory?.provider || "n/a"} · eventos ${aiTaskHistory?.eventsTotal || 0}`, ...(aiTaskHistory?.activeRun?.id ? [`Run: ${aiTaskHistory.activeRun.id}`] : []), ...(aiTaskHistory?.error ? [`Erro: ${aiTaskHistory.error}`] : [])] }} title="AI Task" />
  </div>;
}
