import { LOG_PANES } from "./consoleSummary";
import InternoConsoleHistoryTab from "./InternoConsoleHistoryTab";
import InternoConsoleIssuePane from "./InternoConsoleIssuePane";
import InternoConsoleLogAnalytics from "./InternoConsoleLogAnalytics";
import InternoConsoleLogEntryCard from "./InternoConsoleLogEntryCard";
import InternoConsoleLogInsights from "./InternoConsoleLogInsights";
import InternoConsoleNotesPanel from "./InternoConsoleNotesPanel";

export default function InternoConsolePaneBody(props) {
  const { SPECIAL_LOG_PANES, TAG_LOG_PANES, activityLog, fingerprintStates, frontendForm, frontendIssues, getFingerprintStatusTone, getSeverityTone, handleAddFrontendIssue, handleAddNote, handleAddSchemaIssue, handleBulkFingerprintReset, handleBulkFingerprintStateChange, handleCopyAiTaskHistory, handleCopyContactsHistory, handleCopyDotobotHistory, handleCopyFrontendIssues, handleCopyProcessHistory, handleCopyPublicacoesHistory, handleCopySchemaIssues, handleFingerprintNote, handleFingerprintStateChange, isLightTheme, logExpanded, logFilters, logPane, logSearch, noteInput, operationalNotes, paneBulkGuardrail, paneEntries, paneFingerprintSummary, paneRecommendationSummary, paneRisk, paneSla, paneTagPlaybook, paneTimeline, processosLocalHistory, processosRemoteHistory, publicacoesLocalHistory, publicacoesRemoteHistory, schemaForm, schemaIssues, setFrontendForm, setLogExpanded, setLogSearch, setNoteInput, setSchemaForm, unclassifiedTagEntriesCount, updateFilters, aiTaskHistory, contactsHistory, dotobotHistory } = props;
  const activePane = LOG_PANES.find((pane) => pane.key === logPane);
  const noteClass = isLightTheme ? "border-[#D7DEE8] bg-white" : "border-[#1E2E29] bg-[rgba(10,12,11,0.6)]";
  const badgeClass = isLightTheme ? "border-[#D7DEE8] bg-white text-[#6B7C88]" : "border-[#22342F] text-[#9BAEA8]";
  return <>
    {!SPECIAL_LOG_PANES.has(logPane) ? <div className={`flex flex-wrap items-center gap-2 rounded-xl border p-3 text-[10px] uppercase tracking-[0.14em] ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#7B8B98]" : "border-[#1E2E29] bg-[rgba(10,12,11,0.6)] text-[#7F928C]"}`}>
      <span>Filtros</span>
      {[["module", "Modulo", "w-[110px]"], ["page", "Pagina", "w-[140px]"], ["component", "Componente", "w-[140px]"], ["status", "Status", "w-[90px]"], ["tag", "Tag", "w-[90px]"]].map(([key, placeholder, size]) => <input key={key} value={logFilters[key] || ""} onChange={(event) => updateFilters({ ...logFilters, [key]: event.target.value })} placeholder={placeholder} className={`h-7 ${size} rounded-full border bg-transparent px-2 text-[10px] outline-none ${isLightTheme ? "border-[#D7DEE8] text-[#51606B] placeholder:text-[#93A1AD]" : "border-[#22342F] text-[#E6E0D3] placeholder:text-[#53625C]"}`} />)}
      <input value={logSearch} onChange={(event) => setLogSearch(event.target.value)} placeholder="Buscar detalhes" className={`h-7 min-w-[160px] flex-1 rounded-full border bg-transparent px-2 text-[10px] outline-none ${isLightTheme ? "border-[#D7DEE8] text-[#51606B] placeholder:text-[#93A1AD]" : "border-[#22342F] text-[#E6E0D3] placeholder:text-[#53625C]"}`} />
      {[["severity:error", "So erro", "border-[#5B2D2D] text-[#FECACA] transition hover:border-[#FCA5A5]"], ["severity:warn", "So warn", "border-[#6E5630] text-[#FDE68A] transition hover:border-[#FDE68A]"]].map(([tag, label, tone]) => <button key={tag} type="button" onClick={() => updateFilters({ ...logFilters, tag })} className={`rounded-full border px-3 py-1 text-[10px] ${tone}`}>{label}</button>)}
      <button type="button" onClick={() => { setLogSearch(""); updateFilters({}); }} className={`rounded-full border px-3 py-1 text-[10px] transition hover:border-[#C5A059] hover:text-[#C5A059] ${badgeClass}`}>Limpar filtros</button>
    </div> : null}
    <div className={`sticky top-0 z-10 -mx-4 border-b px-4 py-3 backdrop-blur md:-mx-5 md:px-5 ${isLightTheme ? "border-[#D7DEE8] bg-[rgba(247,249,252,0.94)]" : "border-[#1E2E29] bg-[rgba(8,10,9,0.92)]"}`}>
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div><p className={`text-[10px] uppercase tracking-[0.2em] ${isLightTheme ? "text-[#7B8B98]" : "text-[#6F837B]"}`}>Fluxo ativo</p><p className={`mt-1 text-sm font-semibold ${isLightTheme ? "text-[#152421]" : "text-[#F5F1E8]"}`}>{activePane?.label || logPane}</p></div>
        <div className={`flex flex-wrap items-center gap-2 font-mono text-[11px] ${isLightTheme ? "text-[#51606B]" : "text-[#C7D0CA]"}`}><span>{paneEntries.length} visiveis</span><span className="opacity-45">/</span><span>{activityLog.length} totais</span>{logFilters?.module ? <span className={`rounded-full border px-2 py-1 font-sans text-[10px] uppercase tracking-[0.14em] ${badgeClass}`}>modulo {logFilters.module}</span> : null}{logFilters?.tag ? <span className={`rounded-full border px-2 py-1 font-sans text-[10px] uppercase tracking-[0.14em] ${badgeClass}`}>tag {logFilters.tag}</span> : null}</div>
      </div>
    </div>
    {TAG_LOG_PANES.has(logPane) ? <div className={`rounded-xl border p-3 text-[11px] ${isLightTheme ? "border-[#D7DEE8] bg-[#F7F9FC] text-[#6B7C88]" : "border-[#1E2E29] bg-[rgba(10,12,11,0.6)] text-[#9BAEA8]"}`}>Trilha automatica por tag: <span className="text-[#F4E7C2]">{activePane?.label || logPane}</span>. Os eventos entram aqui pela taxonomia do console.{!paneEntries.length && unclassifiedTagEntriesCount ? <span className={`mt-2 block ${isLightTheme ? "text-[#5B6670]" : "text-[#C7D0CA]"}`}>Nenhuma entrada classificada nesta trilha. Existem {unclassifiedTagEntriesCount} evento(s) ainda sem tag automatica compativel.</span> : null}</div> : null}
    {!SPECIAL_LOG_PANES.has(logPane) && paneEntries.length ? <div className="grid gap-3 xl:grid-cols-2">
      <InternoConsoleLogInsights getSeverityTone={getSeverityTone} isLightTheme={isLightTheme} logFilters={logFilters} logPane={logPane} noteClass={noteClass} paneBulkGuardrail={paneBulkGuardrail} paneRisk={paneRisk} paneSla={paneSla} paneTagPlaybook={paneTagPlaybook} updateFilters={updateFilters} />
      <InternoConsoleLogAnalytics getFingerprintStatusTone={getFingerprintStatusTone} getSeverityTone={getSeverityTone} handleBulkFingerprintReset={handleBulkFingerprintReset} handleBulkFingerprintStateChange={handleBulkFingerprintStateChange} handleFingerprintNote={handleFingerprintNote} handleFingerprintStateChange={handleFingerprintStateChange} isLightTheme={isLightTheme} paneFingerprintSummary={paneFingerprintSummary} paneRecommendationSummary={paneRecommendationSummary} paneTimeline={paneTimeline} />
    </div> : null}
    {logPane === "history" ? <InternoConsoleHistoryTab aiTaskHistory={aiTaskHistory} contactsHistory={contactsHistory} dotobotHistory={dotobotHistory} handleCopyAiTaskHistory={handleCopyAiTaskHistory} handleCopyContactsHistory={handleCopyContactsHistory} handleCopyDotobotHistory={handleCopyDotobotHistory} handleCopyProcessHistory={handleCopyProcessHistory} handleCopyPublicacoesHistory={handleCopyPublicacoesHistory} isLightTheme={isLightTheme} processosLocalHistory={processosLocalHistory} processosRemoteHistory={processosRemoteHistory} publicacoesLocalHistory={publicacoesLocalHistory} publicacoesRemoteHistory={publicacoesRemoteHistory} /> : null}
    <InternoConsoleIssuePane frontendForm={frontendForm} frontendIssues={frontendIssues} handleAddFrontendIssue={handleAddFrontendIssue} handleAddSchemaIssue={handleAddSchemaIssue} handleCopyFrontendIssues={handleCopyFrontendIssues} handleCopySchemaIssues={handleCopySchemaIssues} isLightTheme={isLightTheme} logPane={logPane} schemaForm={schemaForm} schemaIssues={schemaIssues} setFrontendForm={setFrontendForm} setSchemaForm={setSchemaForm} />
    {paneEntries.length ? <div className="space-y-2">{paneEntries.slice(0, 30).map((entry) => <InternoConsoleLogEntryCard key={entry.id} entry={entry} fingerprintStates={fingerprintStates} getFingerprintStatusTone={getFingerprintStatusTone} getSeverityTone={getSeverityTone} handleFingerprintNote={handleFingerprintNote} handleFingerprintStateChange={handleFingerprintStateChange} isLightTheme={isLightTheme} logExpanded={logExpanded} setLogExpanded={setLogExpanded} />)}</div> : !SPECIAL_LOG_PANES.has(logPane) ? <div className="text-[11px] opacity-60">{logPane === "debug" ? "Nenhum debug UI registrado." : `Nenhuma entrada classificada em ${activePane?.label || logPane}.`}</div> : null}
    {logPane === "notes" ? <InternoConsoleNotesPanel handleAddNote={handleAddNote} isLightTheme={isLightTheme} noteInput={noteInput} operationalNotes={operationalNotes} setNoteInput={setNoteInput} /> : null}
  </>;
}
