import DotobotCopilot from "../DotobotPanel";
import OperationalRightRail from "./OperationalRightRail";

export default function InternoRightRailShell(props) {
  const { copilotOpen, currentModuleKey, currentOperationalRail, handleToggleCopilot, isLightTheme, profile, resolvedRightRail, rightCollapsed, rightRailConversationFirst, rightRailFullscreen, routePath, setConsoleOpen, setConsoleTab, setLogPane, shouldRenderDotobotRail, showSupplementalRightRail, updateFilters } = props;
  const openConsole = () => { setConsoleOpen(true); setConsoleTab("console"); };
  const openJobsLog = () => { setConsoleOpen(true); setConsoleTab("log"); setLogPane("jobs"); updateFilters({ module: currentModuleKey, tag: "jobs" }); };
  const supplementalRail = currentOperationalRail ? <OperationalRightRail data={currentOperationalRail} onOpenConsole={openConsole} onOpenJobsLog={openJobsLog} /> : null;

  return <>
    {shouldRenderDotobotRail && !rightCollapsed ? <div className={`fixed inset-y-3 right-3 z-40 flex w-[min(100vw-0.75rem,432px)] flex-col overflow-hidden rounded-[30px] border shadow-[-24px_0_56px_rgba(0,0,0,0.28),inset_0_1px_0_rgba(255,255,255,0.02)] xl:relative xl:inset-y-auto xl:right-auto xl:z-auto xl:h-full xl:min-w-[332px] xl:max-w-[432px] xl:rounded-[30px] xl:shadow-none ${isLightTheme ? "border-[#D4DEE8] bg-[linear-gradient(180deg,rgba(255,255,255,0.985),rgba(243,247,251,0.98))]" : "border-[#22342F] bg-[linear-gradient(180deg,rgba(8,10,9,0.985),rgba(7,9,8,0.96))]"} ${rightRailFullscreen ? "xl:w-[404px]" : "xl:w-[356px]"}`}>{!rightRailConversationFirst && showSupplementalRightRail ? <div className={`max-h-[42%] shrink-0 overflow-auto border-b p-4 xl:max-h-[48%] ${isLightTheme ? "border-[#D7DEE8] bg-[rgba(247,249,252,0.92)]" : "border-[#22342F] bg-[rgba(255,255,255,0.02)]"}`}>{supplementalRail}{resolvedRightRail ? <div className={currentOperationalRail ? "mt-4" : ""}>{resolvedRightRail}</div> : null}</div> : null}<div className="min-h-0 flex-1">{copilotOpen ? <DotobotCopilot profile={profile} routePath={routePath} initialWorkspaceOpen={true} defaultCollapsed={false} compactRail={!rightRailFullscreen} showCollapsedTrigger={false} embeddedInInternoShell={true} /> : <div className="flex h-full items-center justify-center text-sm text-[#9BAEA8]">Painel direito fechado.</div>}</div>{rightRailConversationFirst && showSupplementalRightRail ? <div className={`max-h-[34%] shrink-0 overflow-auto border-t p-4 ${isLightTheme ? "border-[#D7DEE8] bg-[rgba(247,249,252,0.92)]" : "border-[#22342F] bg-[rgba(255,255,255,0.02)]"}`}>{supplementalRail}{resolvedRightRail ? <div className={currentOperationalRail ? "mt-4" : ""}>{resolvedRightRail}</div> : null}</div> : null}</div> : null}
    {shouldRenderDotobotRail ? <button type="button" onClick={handleToggleCopilot} className="group fixed bottom-24 right-4 z-[80] flex items-center gap-2 rounded-[18px] border border-[#C5A059] bg-[linear-gradient(180deg,#C5A059,#B08B46)] px-4 py-3 text-[11px] font-semibold uppercase tracking-[0.18em] text-[#07110E] shadow-[0_10px_30px_rgba(197,160,89,0.3)]"><span className="inline-flex h-2.5 w-2.5 rounded-full bg-[#07110E]" /><span>{copilotOpen && !rightCollapsed ? "Fechar painel" : "Abrir copilot"}</span></button> : null}
  </>;
}
