export default function InternoConsoleIssuePane(props) {
  const { frontendForm, frontendIssues, handleAddFrontendIssue, handleAddSchemaIssue, handleCopyFrontendIssues, handleCopySchemaIssues, isLightTheme, logPane, schemaForm, schemaIssues, setFrontendForm, setSchemaForm } = props;
  if (logPane !== "frontend" && logPane !== "schema") return null;

  const isFrontend = logPane === "frontend";
  const panelTitle = isFrontend ? "Frontend UX" : "Schema";
  const panelHint = isFrontend ? "Registre bugs de interface e debitos tecnicos por pagina." : "Mapeie rotas quebradas, SQL e ajustes de schema.";
  const handleCopy = isFrontend ? handleCopyFrontendIssues : handleCopySchemaIssues;
  const handleAdd = isFrontend ? handleAddFrontendIssue : handleAddSchemaIssue;

  return <div className={`rounded-xl border p-3 ${isLightTheme ? "border-[#D7DEE8] bg-white" : "border-[#1E2E29] bg-[rgba(8,10,9,0.5)]"}`}>
    <div className="flex flex-wrap items-center justify-between gap-3">
      <div>
        <p className={`text-[10px] uppercase tracking-[0.18em] ${isLightTheme ? "text-[#7B8B98]" : "text-[#7F928C]"}`}>{panelTitle}</p>
        <p className={`mt-1 text-[11px] ${isLightTheme ? "text-[#6B7C88]" : "text-[#9BAEA8]"}`}>{panelHint}</p>
      </div>
      <button type="button" onClick={handleCopy} className={`rounded-full border px-3 py-1 text-[10px] uppercase tracking-[0.14em] transition hover:border-[#C5A059] hover:text-[#C5A059] ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#6B7C88]" : "border-[#22342F] text-[#9BAEA8]"}`}>
        {isFrontend ? "Copiar UX" : "Copiar Schema"}
      </button>
    </div>
    {isFrontend ? <div className={`mt-3 flex flex-wrap gap-2 text-[10px] uppercase tracking-[0.14em] ${isLightTheme ? "text-[#7B8B98]" : "text-[#7F928C]"}`}>
      <input value={frontendForm.page} onChange={(event) => setFrontendForm({ ...frontendForm, page: event.target.value })} placeholder="Pagina" className={`h-7 w-[140px] rounded-full border bg-transparent px-2 text-[10px] outline-none ${isLightTheme ? "border-[#D7DEE8] text-[#51606B] placeholder:text-[#93A1AD]" : "border-[#22342F] text-[#E6E0D3] placeholder:text-[#53625C]"}`} />
      <input value={frontendForm.component} onChange={(event) => setFrontendForm({ ...frontendForm, component: event.target.value })} placeholder="Componente" className={`h-7 w-[160px] rounded-full border bg-transparent px-2 text-[10px] outline-none ${isLightTheme ? "border-[#D7DEE8] text-[#51606B] placeholder:text-[#93A1AD]" : "border-[#22342F] text-[#E6E0D3] placeholder:text-[#53625C]"}`} />
      <input value={frontendForm.status} onChange={(event) => setFrontendForm({ ...frontendForm, status: event.target.value })} placeholder="Status" className={`h-7 w-[110px] rounded-full border bg-transparent px-2 text-[10px] outline-none ${isLightTheme ? "border-[#D7DEE8] text-[#51606B] placeholder:text-[#93A1AD]" : "border-[#22342F] text-[#E6E0D3] placeholder:text-[#53625C]"}`} />
      <input value={frontendForm.detail} onChange={(event) => setFrontendForm({ ...frontendForm, detail: event.target.value })} placeholder="Detalhe do bug/UX" className={`h-7 flex-1 min-w-[220px] rounded-full border bg-transparent px-2 text-[10px] outline-none ${isLightTheme ? "border-[#D7DEE8] text-[#51606B] placeholder:text-[#93A1AD]" : "border-[#22342F] text-[#E6E0D3] placeholder:text-[#53625C]"}`} />
      <button type="button" onClick={handleAdd} className={`rounded-full border px-3 py-1 text-[10px] uppercase tracking-[0.14em] transition hover:border-[#C5A059] hover:text-[#C5A059] ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#6B7C88]" : "border-[#22342F] text-[#9BAEA8]"}`}>Adicionar</button>
    </div> : <div className={`mt-3 flex flex-wrap gap-2 text-[10px] uppercase tracking-[0.14em] ${isLightTheme ? "text-[#7B8B98]" : "text-[#7F928C]"}`}>
      <input value={schemaForm.type} onChange={(event) => setSchemaForm({ ...schemaForm, type: event.target.value })} placeholder="Tipo" className={`h-7 w-[120px] rounded-full border bg-transparent px-2 text-[10px] outline-none ${isLightTheme ? "border-[#D7DEE8] text-[#51606B] placeholder:text-[#93A1AD]" : "border-[#22342F] text-[#E6E0D3] placeholder:text-[#53625C]"}`} />
      <input value={schemaForm.table} onChange={(event) => setSchemaForm({ ...schemaForm, table: event.target.value })} placeholder="Tabela" className={`h-7 w-[140px] rounded-full border bg-transparent px-2 text-[10px] outline-none ${isLightTheme ? "border-[#D7DEE8] text-[#51606B] placeholder:text-[#93A1AD]" : "border-[#22342F] text-[#E6E0D3] placeholder:text-[#53625C]"}`} />
      <input value={schemaForm.column} onChange={(event) => setSchemaForm({ ...schemaForm, column: event.target.value })} placeholder="Coluna" className={`h-7 w-[140px] rounded-full border bg-transparent px-2 text-[10px] outline-none ${isLightTheme ? "border-[#D7DEE8] text-[#51606B] placeholder:text-[#93A1AD]" : "border-[#22342F] text-[#E6E0D3] placeholder:text-[#53625C]"}`} />
      <input value={schemaForm.code} onChange={(event) => setSchemaForm({ ...schemaForm, code: event.target.value })} placeholder="Codigo" className={`h-7 w-[120px] rounded-full border bg-transparent px-2 text-[10px] outline-none ${isLightTheme ? "border-[#D7DEE8] text-[#51606B] placeholder:text-[#93A1AD]" : "border-[#22342F] text-[#E6E0D3] placeholder:text-[#53625C]"}`} />
      <input value={schemaForm.detail} onChange={(event) => setSchemaForm({ ...schemaForm, detail: event.target.value })} placeholder="Detalhe/SQL" className={`h-7 flex-1 min-w-[220px] rounded-full border bg-transparent px-2 text-[10px] outline-none ${isLightTheme ? "border-[#D7DEE8] text-[#51606B] placeholder:text-[#93A1AD]" : "border-[#22342F] text-[#E6E0D3] placeholder:text-[#53625C]"}`} />
      <button type="button" onClick={handleAdd} className={`rounded-full border px-3 py-1 text-[10px] uppercase tracking-[0.14em] transition hover:border-[#C5A059] hover:text-[#C5A059] ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#6B7C88]" : "border-[#22342F] text-[#9BAEA8]"}`}>Adicionar</button>
    </div>}
    {isFrontend ? (frontendIssues.length ? <div className="mt-3 space-y-2">{frontendIssues.slice(0, 8).map((issue) => <div key={issue.id} className={`rounded-lg border px-3 py-2 text-[11px] ${isLightTheme ? "border-[#D7DEE8] bg-[#F7F9FC]" : "border-[#1E2E29] bg-[rgba(10,12,11,0.6)]"}`}><div className="flex items-center justify-between"><span className={`font-semibold ${isLightTheme ? "text-[#152421]" : ""}`}>{issue.page || "pagina n/a"}</span><span className="text-[#D9B46A]">{issue.status || "aberto"}</span></div>{issue.component ? <div className={`mt-1 ${isLightTheme ? "text-[#6B7C88]" : "text-[#9BAEA8]"}`}>{issue.component}</div> : null}<div className={`mt-1 ${isLightTheme ? "text-[#5B6670]" : "text-[#C7D0CA]"}`}>{issue.detail}</div></div>)}</div> : <div className="mt-2 text-[11px] opacity-60">Nenhum bug/UX registrado.</div>) : (schemaIssues.length ? <div className="mt-3 space-y-2">{schemaIssues.slice(0, 8).map((issue) => <div key={issue.id || issue.createdAt} className={`rounded-lg border px-3 py-2 text-[11px] ${isLightTheme ? "border-[#D7DEE8] bg-[#F7F9FC]" : "border-[#1E2E29] bg-[rgba(10,12,11,0.6)]"}`}><div className="flex flex-wrap items-center justify-between gap-2"><span className={`font-semibold ${isLightTheme ? "text-[#152421]" : ""}`}>{issue.issue?.type || "schema_issue"}</span>{issue.issue?.code ? <span className="text-[#D9B46A]">{issue.issue.code}</span> : null}</div><div className={`mt-1 ${isLightTheme ? "text-[#6B7C88]" : "text-[#9BAEA8]"}`}>{issue.issue?.table ? `Tabela: ${issue.issue.table}` : "Tabela: n/a"}{issue.issue?.column ? ` | Coluna: ${issue.issue.column}` : ""}</div>{issue.issue?.detail ? <div className={`mt-1 ${isLightTheme ? "text-[#5B6670]" : "text-[#C7D0CA]"}`}>{issue.issue.detail}</div> : null}</div>)}</div> : <div className="mt-2 text-[11px] opacity-60">Nenhum ponto de schema registrado.</div>)}
  </div>;
}
