export const AGENTLAB_ROLLOUT_PHASES = [
  {
    id: "phase-1",
    title: "Fundacao de dados e observabilidade",
    focus: "Espelhar CRM, consolidar conversas e medir gaps reais de resposta.",
  },
  {
    id: "phase-2",
    title: "Modelo de agente e fluxo conversacional",
    focus: "Refinar persona, fallback, handoff e coleta progressiva.",
  },
  {
    id: "phase-3",
    title: "Knowledge packs e contextos de negocio",
    focus: "Ligar FAQ, respostas predefinidas, CRM e jornada do cliente.",
  },
  {
    id: "phase-4",
    title: "Workflows criticos no Freddy",
    focus: "Status processual, financeiro, agendamento, qualificacao e handoff.",
  },
];

export const AGENTLAB_KNOWLEDGE_PACKS = [
  {
    id: "honorarios",
    title: "Honorarios e pagamentos",
    description: "Parcelamento, cartao, boleto, segunda via e politica financeira.",
    priority: "alta",
  },
  {
    id: "consulta",
    title: "Consulta e agendamento",
    description: "Triagem comercial, agenda, documentos e consulta online/presencial.",
    priority: "alta",
  },
  {
    id: "portal",
    title: "Portal, boletos e documentos",
    description: "Acesso ao portal, envio de arquivos, comprovantes e autosservico.",
    priority: "alta",
  },
  {
    id: "processual",
    title: "Perguntas de processo",
    description: "Perguntas frequentes de andamento, limites do que a IA pode afirmar e regras de handoff.",
    priority: "alta",
  },
];

export const AGENTLAB_WORKFLOW_BACKLOG = [
  {
    id: "wf-status",
    title: "Status do processo",
    outcome: "Responder com seguranca ou transferir com resumo quando houver risco processual.",
  },
  {
    id: "wf-pagamento",
    title: "2a via e pagamento",
    outcome: "Resolver autoatendimento financeiro e reduzir friccao de cobranca.",
  },
  {
    id: "wf-agendamento",
    title: "Agendamento de consulta",
    outcome: "Qualificar, captar dados minimos e conduzir o proximo passo comercial.",
  },
  {
    id: "wf-qualificacao",
    title: "Qualificacao de lead",
    outcome: "Identificar urgencia, perfil da divida e aderencia ao servico.",
  },
  {
    id: "wf-handoff",
    title: "Handoff inteligente",
    outcome: "Transferir com contexto, resumo e motivo da escalacao.",
  },
  {
    id: "wf-contexto",
    title: "Recuperacao de contexto do cliente",
    outcome: "Usar CRM, historico e fase do relacionamento antes de responder.",
  },
];

export const AGENTLAB_WEEKLY_SPRINT = {
  unanswered: "Top 20 unanswered",
  poorResponses: "Top 10 poor responses",
  workflows: "Top 5 workflows novos",
  content: "Top 10 conteudos novos",
};

export const AGENTLAB_CRM_AUTOMATION_RULES = [
  {
    id: "crm-booked",
    event_key: "booked",
    title: "Agendamento criado",
    description: "Criar contexto comercial inicial e iniciar aquecimento da reuniao.",
    pipeline_stage: "Reuniao",
    lifecycle_stage: "Triagem",
    meeting_stage: "Agendamento",
    sequence_name: "Pre-consulta",
    journey_name: "Jornada de confirmacao",
    email_template: "confirmacao_agendamento",
    whatsapp_template: "whatsapp_confirmacao_agendamento",
    enabled: true,
    execution_mode: "semi_auto",
    notes: "Usar links de confirmar, cancelar e remarcar no CRM.",
  },
  {
    id: "crm-confirmed",
    event_key: "confirmed",
    title: "Presenca confirmada",
    description: "Elevar a confianca do lead e preparar briefing da consulta.",
    pipeline_stage: "Reuniao",
    lifecycle_stage: "Conectado",
    meeting_stage: "Confirmação de presença",
    sequence_name: "Lembrete de consulta",
    journey_name: "Jornada de comparecimento",
    email_template: "lembrete_consulta",
    whatsapp_template: "whatsapp_lembrete_consulta",
    enabled: true,
    execution_mode: "semi_auto",
    notes: "Ideal para disparar lembrete automatico e checklist de documentos.",
  },
  {
    id: "crm-attended",
    event_key: "attended",
    title: "Consulta realizada",
    description: "Entrar em pos-consulta comercial e abrir trilha de negociacao.",
    pipeline_stage: "Negociação",
    lifecycle_stage: "Conectado",
    meeting_stage: "Confirmação de presença",
    negotiation_stage: "Envio de Proposta",
    sequence_name: "Follow-up pos-consulta",
    journey_name: "Jornada de proposta",
    email_template: "pos_consulta_proposta",
    whatsapp_template: "whatsapp_pos_consulta",
    enabled: true,
    execution_mode: "manual",
    notes: "Recomendado quando houve aderencia comercial apos a reuniao.",
  },
  {
    id: "crm-no-show",
    event_key: "no_show",
    title: "Ausencia do cliente",
    description: "Recuperar a oportunidade e estimular remarcacao.",
    pipeline_stage: "Reuniao",
    lifecycle_stage: "Pedido de retorno",
    meeting_stage: "Ausência",
    sequence_name: "Recuperacao no-show",
    journey_name: "Jornada de remarcacao",
    email_template: "no_show_recuperacao",
    whatsapp_template: "whatsapp_no_show",
    enabled: true,
    execution_mode: "semi_auto",
    notes: "Deve oferecer link de remarcacao e prazo curto de resposta.",
  },
  {
    id: "crm-proposal-accepted",
    event_key: "proposal_accepted",
    title: "Proposta aceita",
    description: "Mover para fechamento e preparar contrato.",
    pipeline_stage: "Fechamento",
    lifecycle_stage: "Conectado",
    negotiation_stage: "Proposta Aceita",
    closing_stage: "Envio de contrato",
    sequence_name: "Onboarding de fechamento",
    journey_name: "Jornada de contrato",
    email_template: "envio_contrato",
    whatsapp_template: "whatsapp_envio_contrato",
    enabled: true,
    execution_mode: "manual",
    notes: "Normalmente depende de validacao interna antes do envio do contrato.",
  },
];
