import React from "react";
import { useInternalTheme } from "../../../components/interno/InternalThemeProvider";
import RequireAdmin from "../../../components/interno/RequireAdmin";
import {
  ACTION_LABELS,
} from "./constants";
import {
  buildJobPreview,
} from "./action-utils";
import { usePublicacoesAdminFetch } from "./usePublicacoesAdminFetch";
import { usePublicacoesOperationalPlan } from "./usePublicacoesOperationalPlan";
import { usePublicacoesCoreState } from "./usePublicacoesCoreState";
import { usePublicacoesQueueState } from "./usePublicacoesQueueState";
import { usePublicacoesDetailState } from "./usePublicacoesDetailState";
import {
  formatDateTimeLabel,
  formatFallbackReason,
  formatSnapshotLabel,
  formatValidationMeta,
  getPublicacaoSelectionValue,
  isResourceLimitError as detectResourceLimitError,
  validationLabel,
  validationTone,
} from "./publicacoesFormatting";
import { usePublicacoesActivityLog } from "./usePublicacoesActivityLog";
import { PublicacoesScreenBody } from "./PublicacoesScreenBody";
import { usePublicacoesLoaders } from "./usePublicacoesLoaders";
import { usePublicacoesIntegratedRows } from "./usePublicacoesIntegratedRows";
import { usePublicacoesActionSuite } from "./usePublicacoesActionSuite";
import { usePublicacoesEffects } from "./usePublicacoesEffects";
import { usePublicacoesViewState } from "./usePublicacoesViewState";
import { usePublicacoesScreenComposition } from "./usePublicacoesScreenComposition";
import { usePublicacoesQueueInteractions } from "./usePublicacoesQueueInteractions";
import { usePublicacoesScreenRuntime } from "./usePublicacoesScreenRuntime";


function PublicacoesContent() {
  const { isLightTheme } = useInternalTheme();
  const { logUiEvent } = usePublicacoesActivityLog();
  const {
    activeJobId, actionState, backendHealth, copilotContext, copilotQueryAppliedRef, drainInFlight,
    executionHistory, globalError, globalErrorUntil, jobs, lastFocusHash, limit, operationalStatus,
    overview, pageVisible, processNumbers, queueRefreshLog, remoteHistory, setActiveJobId, setActionState,
    setBackendHealth, setCopilotContext, setDrainInFlight, setExecutionHistory, setGlobalError,
    setGlobalErrorUntil, setJobs, setLastFocusHash, setLimit, setOperationalStatus, setOverview,
    setPageVisible, setProcessNumbers, setQueueRefreshLog, setRemoteHistory, setView, view,
  } = usePublicacoesCoreState();
  const {
    heavyQueuesEnabled, integratedCursorTrail, integratedFilters, integratedPage, integratedPageSize,
    integratedQueue, integratedQueueRequestRef, partesCandidates, partesCandidatesRequestRef, partesPage,
    processCandidates, processCandidatesRequestRef, processPage, selectedIntegratedNumbers, selectedPartesKeys,
    selectedProcessKeys, setHeavyQueuesEnabled, setIntegratedCursorTrail, setIntegratedFilters, setIntegratedPage,
    setIntegratedQueue, setPartesCandidates, setPartesPage, setProcessCandidates, setProcessPage,
    setSelectedIntegratedNumbers, setSelectedPartesKeys, setSelectedProcessKeys, setValidationMap, validationMap,
  } = usePublicacoesQueueState();
  const {
    bulkValidationNote, bulkValidationStatus, detailEditForm, detailLinkType, detailState,
    selectedDetailLinkedPartes, selectedDetailPendingPartes, setBulkValidationNote,
    setBulkValidationStatus, setDetailEditForm, setDetailLinkType, setDetailState,
    setSelectedDetailLinkedPartes, setSelectedDetailPendingPartes,
  } = usePublicacoesDetailState();
  const adminFetch = usePublicacoesAdminFetch();
  const {
    loadIntegratedQueue,
    loadJobs,
    loadOverview,
    loadPartesCandidates,
    loadProcessCandidates,
    loadRemoteHistory,
    pushQueueRefresh,
  } = usePublicacoesLoaders({
    adminFetch,
    globalErrorUntil,
    heavyQueuesEnabled,
    integratedCursorTrail,
    integratedFilters,
    integratedPageSize,
    integratedQueue,
    integratedQueueRequestRef,
    isResourceLimitError: detectResourceLimitError,
    partesCandidates,
    partesCandidatesRequestRef,
    processCandidates,
    processCandidatesRequestRef,
    setGlobalError,
    setGlobalErrorUntil,
    setIntegratedCursorTrail,
    setIntegratedQueue,
    setJobs,
    setOverview,
    setPartesCandidates,
    setProcessCandidates,
    setQueueRefreshLog,
    setRemoteHistory,
    setValidationMap,
  });
  const {
    filteredIntegratedRows,
    pagedIntegratedRows,
    selectedProcessNumbers,
    selectedUnifiedNumbers,
  } = usePublicacoesIntegratedRows({
    integratedFilters,
    integratedQueue,
    processCandidates,
    selectedIntegratedNumbers,
    selectedProcessKeys,
    validationMap,
  });
  const {
    goToIntegratedNextPage,
    goToIntegratedPreviousPage,
    toggleIntegratedPage,
    togglePageSelection,
    toggleSelection,
    toggleUnifiedRow,
  } = usePublicacoesQueueInteractions({
    integratedPage,
    integratedPageSize,
    integratedQueue,
    pagedIntegratedRows,
    setIntegratedCursorTrail,
    setIntegratedPage,
    setSelectedIntegratedNumbers,
  });
  const {
    allIntegratedFilteredSelected,
    allIntegratedPageSelected,
    blockingJob,
    candidateQueueErrorCount,
    candidateQueueMismatchCount,
    canManuallyDrainActiveJob,
    currentDrainJobId,
    hasBlockingJob,
    hasMultipleBlockingJobs,
    integratedCanGoNext,
    integratedCanGoPrevious,
    integratedSourceLabel,
    latestHistory,
    latestJob,
    latestRemoteRun,
    noPublicationActivityTypeConfigured,
    operationalPlan,
    partesBacklogCount,
    pendingJobCount,
    primaryPublicacoesAction,
    priorityBatchReady,
    publicationActivityTypeHint,
    publicationActivityTypes,
    queueDiagnostics,
    recurringPublicacoes,
    recurringPublicacoesActions,
    recurringPublicacoesBands,
    recurringPublicacoesBatch,
    recurringPublicacoesChecklist,
    recurringPublicacoesFocus,
    recurringPublicacoesGroups,
    recurringPublicacoesSummary,
    remoteHealth,
    selectedUnifiedCount,
    selectedVisibleSevereRecurringCount,
    snapshotMesaIntegrada,
    snapshotPartes,
    snapshotProcessos,
    syncWorkerLastPublicacoes,
    adviseBackfillProgress,
    adviseCursor,
    adviseLastCycleTotal,
    adviseLastRunAt,
    adviseMode,
    advisePersistedDelta,
    adviseSync,
    adviseTokenOk,
    isDockedPublicacoesView,
    isResultView,
    runOperationalPlanStep,
    getOperationalPlanStepState,
    healthSuggestedActions,
    visibleRecurringCount,
    visibleSevereRecurringCount,
    syncWorkerShouldFocusCrm,
  } = usePublicacoesViewState({
    activeJobId,
    data: overview.data || {},
    executionHistory,
    filteredIntegratedRows,
    integratedPage,
    integratedPageSize,
    integratedQueue,
    jobs,
    limit,
    pagedIntegratedRows,
    partesCandidates,
    processCandidates,
    remoteHistory,
    selectedIntegratedNumbers,
    selectedPartesKeys,
    selectedProcessKeys,
    view,
  });
  const {
    applySevereRecurringPreset,
    applyValidationToNumbers,
    clearQueueSelections,
    handleAction,
    linkPendingDetailPartes,
    loadHeavyQueueReads,
    loadIntegratedDetail,
    moveLinkedDetailPartes,
    refreshAfterAction,
    refreshIntegratedSnapshot,
    refreshOperationalContext,
    reclassifyLinkedDetailPartes,
    runBulkContactsReconcile,
    runPendingJobsNow,
    saveDetailContact,
    selectVisibleRecurringPublicacoes,
    selectVisibleSevereRecurringPublicacoes,
    toggleDetailLinkedPage,
    toggleDetailLinkedParte,
    toggleDetailPendingPage,
    toggleDetailPendingParte,
    toggleIntegratedFiltered,
    unlinkLinkedDetailPartes,
    updateView,
  } = usePublicacoesActionSuite({
    activeJobId,
    adminFetch,
    blockingJob,
    canManuallyDrainActiveJob,
    currentDrainJobId,
    detailEditForm,
    detailLinkType,
    detailState,
    filteredIntegratedRows,
    getPublicacaoSelectionValue,
    hasBlockingJob,
    heavyQueuesEnabled,
    integratedFilters,
    integratedPage,
    integratedPageSize,
    integratedQueue,
    jobs,
    limit,
    loadIntegratedQueue,
    loadJobs,
    loadOverview,
    loadPartesCandidates,
    loadProcessCandidates,
    loadRemoteHistory,
    logUiEvent,
    overview: overview.data,
    partesCandidates,
    partesPage,
    partsBacklogCount: partesBacklogCount,
    processCandidates,
    processNumbers,
    processPage,
    pushQueueRefresh,
    recurringPublicacoes,
    recurringPublicacoesBatch,
    recurringPublicacoesSummary,
    selectedDetailLinkedPartes,
    selectedDetailPendingPartes,
    selectedIntegratedNumbers,
    selectedPartesKeys,
    selectedProcessKeys,
    selectedUnifiedNumbers,
    setActionState,
    setActiveJobId,
    setDetailEditForm,
    setDetailState,
    setExecutionHistory,
    setGlobalError,
    setGlobalErrorUntil,
    setHeavyQueuesEnabled,
    setIntegratedCursorTrail,
    setIntegratedPage,
    setLastFocusHash,
    setLimit,
    setOverview,
    setProcessNumbers,
    setRemoteHistory,
    setSelectedDetailLinkedPartes,
    setSelectedDetailPendingPartes,
    setSelectedIntegratedNumbers,
    setSelectedPartesKeys,
    setSelectedProcessKeys,
    setValidationMap,
    setView,
    syncWorkerShouldFocusCrm,
    view,
  });
  usePublicacoesEffects({
    ACTION_LABELS,
    actionState,
    activeJobId,
    adminFetch,
    backendHealth,
    buildJobPreview,
    copilotQueryAppliedRef,
    detailState,
    executionHistory,
    globalError,
    heavyQueuesEnabled,
    integratedCursorTrail,
    integratedFilters,
    integratedPage,
    integratedPageSize,
    integratedQueue,
    jobs,
    lastFocusHash,
    limit,
    loadIntegratedQueue,
    loadJobs,
    loadOverview,
    loadPartesCandidates,
    loadProcessCandidates,
    loadRemoteHistory,
    operationalStatus,
    overview,
    pageVisible,
    partesCandidates,
    partesPage,
    processCandidates,
    processPage,
    queueRefreshLog,
    refreshAfterAction,
    refreshOperationalContext,
    remoteHistory,
    selectedPartesKeys,
    selectedProcessKeys,
    setActionState,
    setActiveJobId,
    setBackendHealth,
    setCopilotContext,
    setDetailState,
    setDrainInFlight,
    setExecutionHistory,
    setLastFocusHash,
    setOperationalStatus,
    setPageVisible,
    setProcessNumbers,
    setSelectedDetailLinkedPartes,
    setSelectedDetailPendingPartes,
    setValidationMap,
    setView,
    validationMap,
    view,
  });




  const data = overview.data || {};
  const {
    getOperationalPlanStepState,
    runOperationalPlanStep,
  } = usePublicacoesOperationalPlan({
    actionState,
    latestHistory,
    handleAction,
    refreshIntegratedSnapshot,
    updateView,
  });
  const {
    healthSuggestedActions,
    remoteHealth,
  } = usePublicacoesDashboardState({
    actionState,
    activeJobId,
    backendHealth,
    blockingState: {
      blockingJob,
      candidateQueueErrorCount,
      candidateQueueMismatchCount,
      canManuallyDrainActiveJob,
      currentDrainJobId,
      hasBlockingJob,
      hasMultipleBlockingJobs,
    },
    data,
    drainInFlight,
    handleAction,
    jobs,
    partesCandidates,
    processCandidates,
    refreshIntegratedSnapshot,
    remoteHistory,
    runPendingJobsNow,
    updateView,
  });
  const screenBodyProps = usePublicacoesScreenComposition({
    actionState,
    activeJobId,
    adviseBackfillProgress,
    adviseCursor,
    adviseLastCycleTotal,
    adviseLastRunAt,
    adviseMode,
    advisePersistedDelta,
    adviseSync,
    adviseTokenOk,
    allIntegratedFilteredSelected,
    allIntegratedPageSelected,
    applySevereRecurringPreset,
    applyValidationToNumbers,
    backendHealth,
    blockingJob,
    bulkValidationNote,
    bulkValidationStatus,
    canManuallyDrainActiveJob,
    candidateQueueErrorCount,
    candidateQueueMismatchCount,
    clearQueueSelections,
    copilotContext,
    data,
    detailEditForm,
    detailLinkType,
    detailState,
    drainInFlight,
    executionHistory,
    filteredIntegratedRows,
    formatDateTimeLabel,
    formatFallbackReason,
    formatSnapshotLabel,
    formatValidationMeta,
    getOperationalPlanStepState,
    getPublicacaoSelectionValue,
    goToIntegratedNextPage,
    goToIntegratedPreviousPage,
    handleAction,
    hasBlockingJob,
    hasMultipleBlockingJobs,
    healthSuggestedActions,
    heavyQueuesEnabled,
    integratedCanGoNext,
    integratedCanGoPrevious,
    integratedFilters,
    integratedPage,
    integratedPageSize,
    integratedQueue,
    integratedSourceLabel,
    isDockedPublicacoesView,
    isLightTheme,
    isResultView,
    jobs,
    latestHistory,
    latestJob,
    latestRemoteRun,
    limit,
    linkPendingDetailPartes,
    loadHeavyQueueReads,
    loadIntegratedDetail,
    loadOverview,
    loadPartesCandidates,
    loadProcessCandidates,
    moveLinkedDetailPartes,
    noPublicationActivityTypeConfigured,
    operationalPlan,
    operationalStatus,
    pagedIntegratedRows,
    partesBacklogCount,
    partesCandidates,
    partesPage,
    pendingJobCount,
    primaryPublicacoesAction,
    priorityBatchReady,
    processCandidates,
    processNumbers,
    processPage,
    publicationActivityTypeHint,
    publicationActivityTypes,
    queueDiagnostics,
    queueRefreshLog,
    reclassifyLinkedDetailPartes,
    recurringPublicacoes,
    recurringPublicacoesActions,
    recurringPublicacoesBands,
    recurringPublicacoesBatch,
    recurringPublicacoesChecklist,
    recurringPublicacoesFocus,
    recurringPublicacoesGroups,
    recurringPublicacoesSummary,
    refreshIntegratedSnapshot,
    remoteHealth,
    remoteHistory,
    runBulkContactsReconcile,
    runOperationalPlanStep,
    runPendingJobsNow,
    saveDetailContact,
    selectedDetailLinkedPartes,
    selectedDetailPendingPartes,
    selectedPartesKeys,
    selectedProcessKeys,
    selectedProcessNumbers,
    selectedUnifiedCount,
    selectedUnifiedNumbers,
    selectedVisibleSevereRecurringCount,
    selectVisibleRecurringPublicacoes,
    selectVisibleSevereRecurringPublicacoes,
    setBulkValidationNote,
    setBulkValidationStatus,
    setDetailEditForm,
    setDetailLinkType,
    setIntegratedFilters,
    setLimit,
    setPartesPage,
    setProcessNumbers,
    setProcessPage,
    setSelectedPartesKeys,
    snapshotMesaIntegrada,
    snapshotPartes,
    snapshotProcessos,
    syncWorkerLastPublicacoes,
    toggleDetailLinkedPage,
    toggleDetailLinkedParte,
    toggleDetailPendingPage,
    toggleDetailPendingParte,
    toggleIntegratedFiltered,
    toggleIntegratedPage,
    togglePageSelection,
    toggleSelection,
    toggleUnifiedRow,
    unlinkLinkedDetailPartes,
    updateView,
    validationLabel,
    validationTone,
    view,
    visibleRecurringCount,
    visibleSevereRecurringCount,
  });

  return (
    <PublicacoesScreenBody {...screenBodyProps} />
  );
}

export default function PublicacoesScreen() {
  return (
    <RequireAdmin>
      <PublicacoesContent />
    </RequireAdmin>
  );
}

