import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const KEYS = [
  "AGENTLAB_REMOTE_DASHBOARD_URL","CF_ACCOUNT_ID","CLOUDFLARE_ACCOUNT_ID",
  "CLOUDFLARE_WORKERS_AI_MODEL","CLOUDFLARE_WORKER_ACCOUNT_ID",
  "FRESHDESK_DOMAIN","FRESHDESK_NEW_TICKET_URL","FRESHDESK_PORTAL_TICKET_BASE_URL",
  "FRESHSALES_ACCESS_TOKEN_URL","FRESHSALES_ACTIVITY_TYPE_AUDIENCIA",
  "FRESHSALES_ACTIVITY_TYPE_BY_EVENT","FRESHSALES_ACTIVITY_TYPE_NOTA_PROCESSUAL",
  "FRESHSALES_ALIAS_DOMAIN","FRESHSALES_API_BASE","FRESHSALES_APPOINTMENT_FIELD_MAP",
  "FRESHSALES_AUTH_MODE","FRESHSALES_BILLING_DEAL_FIELD_MAP",
  "FRESHSALES_CONTACTS_SCOPES","FRESHSALES_CONTACT_CLIENT_FIELD",
  "FRESHSALES_CONTACT_CLOSING_FIELD","FRESHSALES_CONTACT_LIFECYCLE_FIELD",
  "FRESHSALES_CONTACT_MEETING_FIELD","FRESHSALES_CONTACT_NEGOTIATION_FIELD",
  "FRESHSALES_DEALS_SCOPES","FRESHSALES_DEFAULT_DEAL_STAGE_ID",
  "FRESHSALES_DOMAIN","FRESHSALES_FINANCE_ACCOUNT_PROCESS_FIELDS",
  "FRESHSALES_FINANCE_ACCOUNT_STATUS_FIELDS","FRESHSALES_FINANCE_DEAL_STAGE_FIELDS",
  "FRESHSALES_FINANCE_DEAL_TYPE_FIELDS","FRESHSALES_FINANCIAL_EVENT_STAGE_MAP",
  "FRESHSALES_OAUTH_CALLBACK_URL","FRESHSALES_OWNER_ID","FRESHSALES_REDIRECT_URI",
  "FRESHSALES_SCOPES","FRESHSALES_STAGE_VALUE_MAP","FRESHWORKS_ORG_DOMAIN",
  "HMADV_RUNNER_URL","MAIL_FROM","MAIL_HOST","MAIL_PORT","MAIL_SECURE",
  "MAIL_USER","NEXT_PUBLIC_FRESHWORKS_WIDGET_CHAT",
  "NEXT_PUBLIC_FRESHWORKS_WIDGET_SCRIPT_URL","NEXT_PUBLIC_SUPPORT_CHANNEL",
  "PROCESS_AI_BASE","SITE_URL","SLACK_WEBHOOK_URL",
  "ZOOM_ACCOUNT_ID","ZOOM_DEFAULT_TIMEZONE","ZOOM_USER_ID"
];

serve(async (_req) => {
  const result: Record<string, string> = {};
  for (const key of KEYS) {
    result[key] = Deno.env.get(key) ?? "";
  }
  return new Response(JSON.stringify(result, null, 2), {
    headers: { "Content-Type": "application/json" }
  });
});
