name = "hmadv-api"
main = "src/index.ts"
compatibility_date = "2026-03-31"
workers_dev = false

routes = [
  { pattern = "api.hermidamaia.adv.br", custom_domain = true }
]

[triggers]
crons = ["0 7 * * *"]

[vars]
# Adicione variáveis de ambiente necessárias aqui
