export default function DotobotWorkspaceHeader(props) {
  const { activeBrowserProfile, activeConversation, activeConversationPreview, activeConversationTimestamp, activeProviderPresentation, activeStatus, activeTaskLabel, activeTaskProviderLabel, activeTaskStepCount, capabilitiesCommands, capabilitiesSkills, createConversation, fullscreenConversationSubtitle, handleApprove, handleContinueLastRun, handleCopilotDebug, handleOpenLlmTest, handlePauseFlow, isCompactViewport, isFocusedCopilotShell, isLightTheme, localInferenceAlert, localRuntimeConfigOpen, localRuntimeLabel, localStackLabel, localStackSummary, localStackTone, localTaskCount, messageCount, onRefreshLocalStack, onToggleCollapse, onToggleLocalRuntimeConfig, paused, ragAlert, refreshingLocalStack, showConversationCockpitCards, showRuntimeOpsHeader, uiStateLabel, visibleConversationCount } = props;
  const introText = isFocusedCopilotShell ? fullscreenConversationSubtitle : isCompactViewport ? "Chat inteligente para orientar proximas acoes." : "Conversa assistida com contexto, historico e proximos passos em um so lugar.";
  const localSummary = localStackSummary?.ok && localStackSummary?.localProvider?.available ? `Modo local disponivel${localStackSummary.offlineMode ? " em operacao offline" : ""} com ${localStackSummary.localProvider?.model || "modelo local"}.` : "O modo local ainda nao respondeu; siga com a nuvem principal ou ative sua infraestrutura local quando precisar.";

  return (
    <header className={`border-b px-4 py-4 ${isLightTheme ? "border-[#D7DEE8]" : "border-[#22342F]"}`}>
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <p className={`text-[10px] uppercase tracking-[0.16em] ${isLightTheme ? "text-[#7B8B98]" : "text-[#7F928C]"}`}>Copilot</p>
          <div className="mt-2 flex items-center gap-3"><h3 className={`text-lg font-semibold tracking-[-0.02em] ${isLightTheme ? "text-[#152421]" : "text-[#F5F1E8]"}`}>Dotobot</h3><span className={`inline-flex items-center gap-2 rounded-full border px-2.5 py-1 text-[10px] uppercase tracking-[0.16em] ${activeStatus === "processing" ? "border-[#8b6f33] text-[#D9B46A]" : "border-[#234034] text-[#80C7A1]"}`}><span className={`h-2 w-2 rounded-full ${activeStatus === "processing" ? "bg-[#D9B46A]" : "bg-[#80C7A1]"}`} />{activeStatus === "processing" ? uiStateLabel : "Idle"}</span></div>
          <p className={`mt-2 max-w-md text-xs leading-6 ${isLightTheme ? "text-[#6B7C88]" : "text-[#8FA19B]"}`}>{introText}</p>
          <div className="mt-3 flex flex-wrap gap-2 text-[11px]"><span className={`rounded-full border px-3 py-1.5 ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#51606B]" : "border-[#22342F] text-[#D8DEDA]"}`}>Provider: {activeProviderPresentation.name}</span>{!isFocusedCopilotShell ? <span className={`rounded-full border px-3 py-1.5 ${localStackTone}`}>{localStackLabel}</span> : null}{activeProviderPresentation.meta.map((item) => <span key={item} className={`rounded-full border px-3 py-1.5 ${isLightTheme ? "border-[#D7DEE8] bg-[#F7F9FC] text-[#6B7C88]" : "border-[#22342F] text-[#9BAEA8]"}`}>{item}</span>)}{!isFocusedCopilotShell && localStackSummary?.runtimeBaseUrl ? <span className="rounded-full border border-[#35554B] px-3 py-1.5 text-[#B7D5CB]">runtime {localStackSummary.runtimeBaseUrl}</span> : null}{!isFocusedCopilotShell && localStackSummary?.localProvider?.transport ? <span className="rounded-full border border-[#35554B] px-3 py-1.5 text-[#B7D5CB]">{localRuntimeLabel || localStackSummary.localProvider?.runtimeLabel || "Runtime local"}</span> : null}{!isFocusedCopilotShell && capabilitiesSkills?.total ? <span className={`rounded-full border px-3 py-1.5 ${isLightTheme ? "border-[#D7DEE8] bg-[#F7F9FC] text-[#6B7C88]" : "border-[#22342F] text-[#9BAEA8]"}`}>Skills {capabilitiesSkills.total}</span> : null}{!isFocusedCopilotShell && capabilitiesCommands?.executable ? <span className={`rounded-full border px-3 py-1.5 ${isLightTheme ? "border-[#D7DEE8] bg-[#F7F9FC] text-[#6B7C88]" : "border-[#22342F] text-[#9BAEA8]"}`}>Comandos {capabilitiesCommands.executable}/{capabilitiesCommands.total}</span> : null}{!isFocusedCopilotShell && activeBrowserProfile?.label ? <span className="rounded-full border border-[#35554B] px-3 py-1.5 text-[#B7D5CB]">Extensao {activeBrowserProfile.label}</span> : null}{!isFocusedCopilotShell && activeProviderPresentation.endpoint ? <span className="rounded-full border border-[#35554B] px-3 py-1.5 text-[#B7D5CB]">{activeProviderPresentation.endpoint}</span> : null}</div>
          {localStackSummary && !isFocusedCopilotShell ? <p className={`mt-2 max-w-2xl text-[11px] leading-6 ${isLightTheme ? "text-[#6B7C88]" : "text-[#7F928C]"}`}>{localSummary}</p> : null}
          {showConversationCockpitCards ? <div className="mt-4 grid gap-3"><div className={`rounded-[20px] border p-4 ${isLightTheme ? "border-[#E6D29A] bg-[radial-gradient(circle_at_top_left,rgba(197,160,89,0.12),transparent_60%),#FFFDF7]" : "border-[#3C3320] bg-[radial-gradient(circle_at_top_left,rgba(197,160,89,0.14),transparent_60%),rgba(255,255,255,0.02)]"}`}><p className={`text-[10px] uppercase tracking-[0.18em] ${isLightTheme ? "text-[#9A6E2D]" : "text-[#D9B46A]"}`}>Resumo</p><p className={`mt-2 text-sm font-semibold ${isLightTheme ? "text-[#152421]" : "text-[#F5F1E8]"}`}>{activeConversation?.title || "Nova conversa"}</p><p className={`mt-2 line-clamp-3 text-[12px] leading-6 ${isLightTheme ? "text-[#51606B]" : "text-[#C6D1CC]"}`}>{activeConversationPreview}</p><div className="mt-3 flex flex-wrap gap-2"><span className={`rounded-full border px-3 py-1.5 text-[10px] ${isLightTheme ? "border-[#E6D29A] bg-[#FFF6DF] text-[#8A6217]" : "border-[#4B3F22] text-[#F1D39A]"}`}>historico {visibleConversationCount}</span><span className={`rounded-full border px-3 py-1.5 text-[10px] ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#51606B]" : "border-[#22342F] text-[#D8DEDA]"}`}>mensagens {messageCount}</span><span className={`rounded-full border px-3 py-1.5 text-[10px] ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#51606B]" : "border-[#22342F] text-[#D8DEDA]"}`}>tarefas {localTaskCount}</span></div></div><div className={`rounded-[20px] border p-4 ${isLightTheme ? "border-[#D7DEE8] bg-white" : "border-[#22342F] bg-[rgba(255,255,255,0.02)]"}`}><div className="flex items-center justify-between gap-3"><div><p className={`text-[10px] uppercase tracking-[0.18em] ${isLightTheme ? "text-[#7B8B98]" : "text-[#7F928C]"}`}>Missao em foco</p><p className={`mt-2 text-sm font-semibold ${isLightTheme ? "text-[#152421]" : "text-[#F5F1E8]"}`}>{activeTaskLabel}</p></div><span className={`rounded-full border px-2.5 py-1 text-[10px] ${localTaskCount ? "border-[#C5A059] text-[#F1D39A]" : "border-[#22342F] text-[#9BAEA8]"}`}>{localTaskCount ? `${localTaskCount} ativa(s)` : "sem execucao"}</span></div><div className="mt-3 flex flex-wrap gap-2"><span className={`rounded-full border px-3 py-1.5 text-[10px] ${isLightTheme ? "border-[#D7DEE8] bg-[#F7F9FC] text-[#51606B]" : "border-[#22342F] text-[#D8DEDA]"}`}>provider {activeTaskProviderLabel}</span><span className={`rounded-full border px-3 py-1.5 text-[10px] ${isLightTheme ? "border-[#D7DEE8] bg-[#F7F9FC] text-[#51606B]" : "border-[#22342F] text-[#D8DEDA]"}`}>etapas {activeTaskStepCount}</span>{activeConversationTimestamp ? <span className={`rounded-full border px-3 py-1.5 text-[10px] ${isLightTheme ? "border-[#D7DEE8] bg-[#F7F9FC] text-[#6B7C88]" : "border-[#22342F] text-[#9BAEA8]"}`}>{new Date(activeConversationTimestamp).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</span> : null}</div></div></div> : null}
          {showRuntimeOpsHeader && localStackSummary?.recommendations?.length ? <div className="mt-2 flex max-w-3xl flex-wrap gap-2 text-[11px]">{localStackSummary.recommendations.slice(0, 3).map((item) => <span key={item} className={`rounded-full border px-3 py-1.5 ${isLightTheme ? "border-[#E6D29A] bg-[#FFF8EA] text-[#8A6217]" : "border-[#3B3523] bg-[rgba(197,160,89,0.08)] text-[#D9C38A]"}`}>{item}</span>)}</div> : null}
          {showRuntimeOpsHeader && activeProviderPresentation.reason ? <p className={`mt-2 max-w-2xl text-[11px] leading-6 ${isLightTheme ? "text-[#6B7C88]" : "text-[#7F928C]"}`}>{activeProviderPresentation.reason}</p> : null}
          {showRuntimeOpsHeader && localInferenceAlert ? <div className={`mt-4 max-w-3xl rounded-[20px] border px-4 py-3 text-sm ${localInferenceAlert.tone === "danger" ? "border-[#5b2d2d] bg-[rgba(91,45,45,0.22)] text-[#f2d0d0]" : "border-[#6f5a2d] bg-[rgba(98,79,34,0.2)] text-[#f1dfb5]"}`}><p className="text-[10px] uppercase tracking-[0.18em] opacity-80">Contingencia local</p><p className={`mt-2 font-medium ${isLightTheme ? "text-[#6A4B12]" : "text-[#F5F1E8]"}`}>{localInferenceAlert.title}</p><p className="mt-1 leading-6">{localInferenceAlert.body}</p></div> : null}
          {showRuntimeOpsHeader && ragAlert ? <div className={`mt-4 max-w-3xl rounded-[20px] border px-4 py-3 text-sm ${ragAlert.tone === "danger" ? "border-[#5b2d2d] bg-[rgba(91,45,45,0.22)] text-[#f2d0d0]" : "border-[#6f5a2d] bg-[rgba(98,79,34,0.2)] text-[#f1dfb5]"}`}><p className="text-[10px] uppercase tracking-[0.18em] opacity-80">Diagnostico RAG</p><p className={`mt-2 font-medium ${isLightTheme ? "text-[#6A4B12]" : "text-[#F5F1E8]"}`}>{ragAlert.title}</p><p className="mt-1 leading-6">{ragAlert.body}</p></div> : null}
        </div>
        <div className="flex w-full flex-wrap items-start gap-2 lg:w-auto lg:justify-end">{showRuntimeOpsHeader ? <><button type="button" onClick={handleCopilotDebug} className={`rounded-2xl border px-3 py-2 text-xs transition ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#51606B] hover:border-[#9A6E2D] hover:text-[#9A6E2D]" : "border-[#22342F] text-[#D8DEDA] hover:border-[#C5A059] hover:text-[#C5A059]"}`}>Debug</button><button type="button" onClick={onRefreshLocalStack} disabled={refreshingLocalStack} className={`rounded-2xl border px-3 py-2 text-xs transition disabled:cursor-wait disabled:opacity-60 ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#51606B] hover:border-[#9A6E2D] hover:text-[#9A6E2D]" : "border-[#22342F] text-[#D8DEDA] hover:border-[#C5A059] hover:text-[#C5A059]"}`}>{refreshingLocalStack ? "Atualizando stack..." : "Atualizar stack local"}</button><button type="button" onClick={onToggleLocalRuntimeConfig} className={`rounded-2xl border px-3 py-2 text-xs transition ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#51606B] hover:border-[#9A6E2D] hover:text-[#9A6E2D]" : "border-[#22342F] text-[#D8DEDA] hover:border-[#C5A059] hover:text-[#C5A059]"}`}>{localRuntimeConfigOpen ? "Fechar runtime local" : "Editar runtime local"}</button><button type="button" onClick={handlePauseFlow} className={`rounded-2xl border px-3 py-2 text-xs transition ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#51606B] hover:border-[#9A6E2D] hover:text-[#9A6E2D]" : "border-[#22342F] text-[#D8DEDA] hover:border-[#C5A059] hover:text-[#C5A059]"}`}>{paused ? "Retomar fluxo" : "Pausar fluxo"}</button><button type="button" onClick={handleContinueLastRun} className={`rounded-2xl border px-3 py-2 text-xs transition ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#51606B] hover:border-[#9A6E2D] hover:text-[#9A6E2D]" : "border-[#22342F] text-[#D8DEDA] hover:border-[#C5A059] hover:text-[#C5A059]"}`}>Retomar falha</button><button type="button" onClick={handleApprove} className="rounded-2xl border border-[#234034] px-3 py-2 text-xs text-[#8FCFA9] transition hover:border-[#8FCFA9]">Aprovar acao</button><button type="button" onClick={handleOpenLlmTest} className={`rounded-2xl border px-3 py-2 text-xs transition ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#51606B] hover:border-[#9A6E2D] hover:text-[#9A6E2D]" : "border-[#22342F] text-[#D8DEDA] hover:border-[#C5A059] hover:text-[#C5A059]"}`}>Testar provider</button></> : null}<button type="button" className="rounded-2xl border border-[#22342F] px-3 py-2 text-xs text-[#D8DEDA] transition hover:border-[#C5A059] hover:text-[#C5A059]" onClick={onToggleCollapse}>Compactar</button></div>
      </div>
    </header>
  );
}
