import DotobotMessageBubble from "./DotobotMessageBubble";

function AttachmentChip({ attachment, formatBytes, isLightTheme }) {
  return (
    <div className={`flex items-center gap-3 rounded-full border px-3 py-2 text-xs ${isLightTheme ? "border-[#D7DEE8] bg-[#F7F9FC] text-[#51606B]" : "border-[#22342F] bg-[rgba(255,255,255,0.02)] text-[#C6D1CC]"}`}>
      {attachment.previewUrl ? <img src={attachment.previewUrl} alt={attachment.name} className="h-8 w-8 rounded-lg object-cover" /> : <span className={`inline-flex h-8 w-8 items-center justify-center rounded-lg border text-[10px] uppercase ${isLightTheme ? "border-[#D7DEE8] text-[#7B8B98]" : "border-[#22342F] text-[#9BAEA8]"}`}>{attachment.kind}</span>}
      <div><p className="max-w-[12rem] truncate">{attachment.name}</p><p className="text-[10px] opacity-60">{formatBytes(attachment.size)} · {attachment.remoteKey ? "R2 sincronizado" : "upload pendente"}</p></div>
    </div>
  );
}

function SyncBadge({ isLightTheme, remoteSyncSummary }) {
  const connected = remoteSyncSummary?.connected;
  const tone = connected
    ? isLightTheme ? "border-[#CFE3DB] bg-[#F5FBF8] text-[#2F7A62]" : "border-[#35554B] text-[#9FE0C7]"
    : isLightTheme ? "border-[#E6D29A] bg-[#FFF8E8] text-[#8A6217]" : "border-[#4B3F22] text-[#F1D39A]";
  return <span className={`rounded-full border px-3 py-1.5 text-[10px] ${tone}`}>{connected ? remoteSyncSummary.loading ? "Cloudflare sync" : "Cloudflare ativo" : "Somente local"}</span>;
}

export default function DotobotEmbeddedStandardRail(props) {
  const { attachments, composerBlockedReason, composerRef, error, formatBytes, handleComposerKeyDown, handleCopyMessage, handleDrop, handleLocalStackAction, handleMessageAction, handleOpenFiles, handleOpenMessageInAiTask, handlePaste, handleQuickAction, handleResetChat, handleReuseMessage, handleSlashCommand, handleSubmit, input, isCompactViewport, isComposerBlocked, isLightTheme, isRecording, loading, localInferenceAlert, messages, onChangeInput, onFocusComposer, onToggleVoiceInput, remoteSyncSummary, scrollRef, showSlashCommands, visibleLegalActions, visibleQuickPrompts, slashCommands } = props;
  const syncedAttachments = remoteSyncSummary?.remoteAttachmentCount || 0;
  return (
    <>
      <div className={`border-b px-4 py-3 ${isLightTheme ? "border-[#D7DEE8]" : "border-[#22342F]"}`}><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex flex-wrap gap-1.5 sm:gap-2">{visibleLegalActions.slice(0, 2).map((action) => <button key={action.label} type="button" onClick={() => handleQuickAction(action.prompt)} className={`rounded-full border px-3 py-1.5 text-[10px] transition sm:text-[11px] ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#51606B] hover:border-[#9A6E2D] hover:text-[#9A6E2D]" : "border-[#22342F] text-[#D9E0DB] hover:border-[#C5A059] hover:text-[#C5A059]"}`}>{action.label}</button>)}</div><div className="flex flex-wrap gap-2"><SyncBadge isLightTheme={isLightTheme} remoteSyncSummary={remoteSyncSummary} />{attachments.length ? <span className={`rounded-full border px-3 py-1.5 text-[10px] ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#51606B]" : "border-[#22342F] text-[#D8DEDA]"}`}>R2 {syncedAttachments}/{attachments.length}</span> : null}</div></div></div>
      <div ref={scrollRef} className="max-h-[42vh] space-y-3 overflow-y-auto px-4 py-4 pr-3 sm:max-h-[50vh] sm:pr-4">
        {messages.length ? <div className="space-y-3">{messages.map((message, index) => <DotobotMessageBubble key={message.id || `${message.role}-${message.createdAt || index}-${index}`} message={message} onCopy={handleCopyMessage} onReuse={handleReuseMessage} onOpenAiTask={handleOpenMessageInAiTask} onAction={handleMessageAction} />)}</div> : <div className={`rounded-[24px] border p-4 text-sm ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#6B7C88]" : "border-[#22342F] bg-[rgba(255,255,255,0.02)] text-[#9BAEA8]"}`}><p className={`font-medium ${isLightTheme ? "text-[#152421]" : "text-[#F5F1E8]"}`}>Pronto para operar.</p><p className="mt-2 leading-7">Envie uma ordem, analise de caso, pedido de fluxo ou instrucao de treinamento. O Dotobot responde em PT-BR, com foco interno, seguranca juridica e proximos passos.</p></div>}
        {loading ? <DotobotMessageBubble message={{ role: "assistant", text: "", createdAt: null }} isTyping={true} /> : null}
        {localInferenceAlert && !messages.length ? <div className={`rounded-[24px] border p-4 text-sm ${isLightTheme ? "border-[#E6D29A] bg-[#FFF8E8] text-[#8A6217]" : "border-[#6f5a2d] bg-[rgba(98,79,34,0.16)] text-[#f1dfb5]"}`}><p className={`font-medium ${isLightTheme ? "text-[#6A4B12]" : "text-[#F5F1E8]"}`}>{localInferenceAlert.title}</p><p className="mt-2 leading-7">{localInferenceAlert.body}</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => handleLocalStackAction("open_runtime_config")} className={`rounded-full border px-3 py-1.5 text-[11px] transition ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#2F7A62] hover:border-[#2F7A62]" : "border-[#35554B] text-[#B7D5CB] hover:border-[#7FC4AF] hover:text-[#7FC4AF]"}`}>Editar runtime local</button><button type="button" onClick={() => handleLocalStackAction("open_ai_task")} className={`rounded-full border px-3 py-1.5 text-[11px] transition ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#2F7A62] hover:border-[#2F7A62]" : "border-[#35554B] text-[#B7D5CB] hover:border-[#7FC4AF] hover:text-[#7FC4AF]"}`}>Continuar via AI Task</button></div></div> : null}
        {error ? <p className={`text-sm ${isLightTheme ? "text-[#B94A48]" : "text-[#f2b2b2]"}`}>{error}</p> : null}
      </div>
      <div className={`border-t px-4 py-4 ${isLightTheme ? "border-[#D7DEE8]" : "border-[#22342F]"}`}>
        <div className="mb-3 flex flex-wrap gap-1.5 sm:gap-2">{visibleQuickPrompts.map((prompt) => <button key={prompt} type="button" className={`rounded-full border px-3 py-1.5 text-[10px] transition sm:text-[11px] ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#51606B] hover:border-[#9A6E2D] hover:text-[#9A6E2D]" : "border-[#22342F] text-[#C6D1CC] hover:border-[#C5A059] hover:text-[#C5A059]"}`} onClick={() => onChangeInput(prompt)}>{prompt}</button>)}</div>
        <form onSubmit={handleSubmit} className="space-y-3">
          <textarea ref={composerRef} value={input} onChange={(event) => onChangeInput(event.target.value)} onKeyDown={handleComposerKeyDown} onPaste={handlePaste} onDragOver={(event) => event.preventDefault()} onDrop={handleDrop} rows={isCompactViewport ? 3 : 4} disabled={isComposerBlocked} placeholder="Descreva a tarefa, caso, ordem do administrador ou instrucao de treinamento..." className={`w-full resize-y rounded-[22px] border px-4 py-3 text-sm outline-none transition disabled:cursor-not-allowed disabled:opacity-50 ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#152421] placeholder:text-[#94A3B8] focus:border-[#9A6E2D]" : "border-[#22342F] bg-[rgba(7,9,8,0.98)] focus:border-[#C5A059]"}`} />
          {composerBlockedReason ? <p className={`text-[11px] leading-5 ${isLightTheme ? "text-[#8A6217]" : "text-[#f1dfb5]"}`}>{composerBlockedReason}</p> : null}
          {attachments.length ? <div className="flex flex-wrap gap-2">{attachments.map((attachment) => <AttachmentChip key={attachment.id} attachment={attachment} formatBytes={formatBytes} isLightTheme={isLightTheme} />)}</div> : null}
          {showSlashCommands && input.trim().startsWith("/") ? <div className={`rounded-[22px] border p-2 ${isLightTheme ? "border-[#D7DEE8] bg-[#F7F9FC]" : "border-[#22342F] bg-[rgba(7,9,8,0.98)]"}`}>{slashCommands.map((command) => <button key={command.value} type="button" onClick={() => handleSlashCommand(command)} className={`flex w-full items-start justify-between gap-4 rounded-2xl px-3 py-2 text-left text-xs transition ${isLightTheme ? "text-[#51606B] hover:bg-white" : "text-[#C6D1CC] hover:bg-[rgba(255,255,255,0.03)]"}`}><span><span className={`font-semibold ${isLightTheme ? "text-[#152421]" : "text-[#F5F1E8]"}`}>{command.label}</span><span className={`ml-2 ${isLightTheme ? "text-[#7B8B98]" : "text-[#9BAEA8]"}`}>{command.value}</span></span><span className={`max-w-[16rem] text-right text-[11px] ${isLightTheme ? "text-[#7B8B98]" : "text-[#9BAEA8]"}`}>{command.hint}</span></button>)}</div> : null}
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="flex flex-wrap gap-2"><button type="button" onClick={handleResetChat} className={`rounded-2xl border px-3 py-2 text-xs transition ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#51606B] hover:border-[#9A6E2D] hover:text-[#9A6E2D]" : "border-[#22342F] text-[#D8DEDA] hover:border-[#C5A059] hover:text-[#C5A059]"}`}>Limpar conversas</button><button type="button" onClick={handleOpenFiles} className={`rounded-2xl border px-3 py-2 text-xs transition ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#51606B] hover:border-[#9A6E2D] hover:text-[#9A6E2D]" : "border-[#22342F] text-[#D8DEDA] hover:border-[#C5A059] hover:text-[#C5A059]"}`}>Anexar arquivos</button><button type="button" onClick={onToggleVoiceInput} className={`rounded-2xl border px-3 py-2 text-xs transition ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#51606B] hover:border-[#9A6E2D] hover:text-[#9A6E2D]" : "border-[#22342F] text-[#D8DEDA] hover:border-[#C5A059] hover:text-[#C5A059]"}`}>{isRecording ? "Parar voz" : "Ditado"}</button><button type="button" onClick={onFocusComposer} className={`rounded-2xl border px-3 py-2 text-xs transition ${isLightTheme ? "border-[#D7DEE8] bg-white text-[#51606B] hover:border-[#9A6E2D] hover:text-[#9A6E2D]" : "border-[#22342F] text-[#D8DEDA] hover:border-[#C5A059] hover:text-[#C5A059]"}`}>Cmd+K</button></div>
            <button type="submit" disabled={loading || !input.trim()} className="rounded-2xl border border-[#C5A059] px-4 py-2 text-sm font-semibold text-[#C5A059] transition disabled:opacity-40">Executar</button>
          </div>
        </form>
      </div>
    </>
  );
}
