import { useMemo } from "react";
import { buildRagAlert, formatHistoryStatus, nowIso } from "./aiTaskMissionBlueprint";
import { detectModules, formatExecutionSourceLabel } from "./aiTaskAdapters";

export default function useAiTaskShellProps(params) {
  return useMemo(
    () => ({
      headerProps: {
        stateLabel: params.derived.stateLabel,
        provider: params.provider,
        contextSnapshot: params.contextSnapshot,
        selectedSkillId: params.selectedSkillId,
        skillOptions: params.skillCatalog,
        providerOptions: params.providerCatalog,
        localStackSummary: params.localStackSummary,
        ragHealth: params.ragHealth,
        ragAlert: buildRagAlert(params.ragHealth),
        onProviderChange: params.setProvider,
        onSkillChange: params.setSelectedSkillId,
        activeModeLabel: params.derived.activeModeLabel,
        executionSource: params.executionSource,
        executionModel: params.executionModel,
        eventsTotal: params.eventsTotal,
        paused: params.paused,
        handlePause: params.handlePause,
        handleStop: params.openStopModal,
        handleContinueLastRun: params.handleContinueLastRun,
        handleApprove: params.handleApprove,
        handleOpenLlmTest: params.handleOpenLlmTest,
        handleOpenDiagnostics: params.handleOpenDiagnostics,
        handleOpenDotobot: params.handleOpenDotobot,
        handleRefreshLocalStack: params.refreshLocalStackStatus,
        handleLocalStackAction: params.handleLocalStackAction,
        localRuntimeConfigOpen: params.localRuntimeConfigOpen,
        onToggleLocalRuntimeConfig: params.toggleLocalRuntimeConfig,
        localRuntimeDraft: params.localRuntimeDraft,
        onLocalRuntimeDraftChange: params.setLocalRuntimeDraft,
        onSaveLocalRuntimeConfig: params.handleSaveLocalRuntimeConfig,
        refreshingLocalStack: params.refreshingLocalStack,
        formatExecutionSourceLabel,
      },
      executionProps: {
        activeRun: params.activeRun,
        attachments: params.attachments,
        compactLogs: params.derived.compactLogs,
        error: params.error,
        handleAttachmentChange: params.handleAttachmentChange,
        handleAttachmentDrop: params.handleAttachmentDrop,
        handleContinueLastRun: params.handleContinueLastRun,
        handleMissionChange: params.handleMissionChange,
        handleQuickMission: params.handleQuickMission,
        handleReplay: params.handleReplay,
        handleSendToDotobot: params.handleSendToDotobot,
        handleStart: params.handleStart,
        latestResult: params.latestResult,
        mission: params.mission,
        missionInputRef: params.missionInputRef,
        moduleDrivenQuickMissions: params.derived.moduleDrivenQuickMissions,
        nowIso,
        paused: params.paused,
        routePath: params.routePath,
        selectedTask: params.derived.selectedTask,
        thinking: params.thinking,
      },
      runsPaneProps: {
        className: "",
        recentHistory: params.recentHistory,
        visibleHistory: params.derived.historyMeta.items,
        activeRunId: params.activeRun?.id || null,
        formatHistoryStatus,
        formatExecutionSourceLabel,
        nowIso,
        onSelectRun: params.handleSelectRun,
        historyPage: params.historyPage,
        historyTotalPages: params.derived.historyMeta.totalPages,
        onPrevPage: params.handlePrevHistoryPage,
        onNextPage: params.handleNextHistoryPage,
      },
      contextRailProps: {
        showContext: params.showContext,
        setShowContext: params.setShowContext,
        contextSnapshot: params.contextSnapshot,
        contextModuleEntries: params.derived.contextModuleEntries,
        mission: params.mission,
        routePath: params.routePath,
        approved: params.approved,
        quickMissions: params.derived.moduleDrivenQuickMissions,
        handleModuleAction: params.handleModuleAction,
        handleQuickMission: params.handleQuickMission,
        selectedTask: params.derived.selectedTask,
        handleSendToDotobot: params.handleSendToDotobot,
        handleReplay: params.handleReplay,
        detectModules,
        contact360Query: params.contact360Query,
        onContact360QueryChange: params.setContact360Query,
        onLoadContact360: params.handleLoadContact360,
        contact360Loading: params.contact360Loading,
        contact360: params.contact360,
      },
    }),
    [params]
  );
}
