export const DOTOBOT_TOOL_CATALOG = [
  {
    id: "pipeline_status",
    title: "Status do pipeline HMADV",
    group: "pipeline",
    visibility: "ready",
    execution: { kind: "edge_function", functionName: "dotobot-slack", action: "status" },
    description: "Mostra panorama operacional de publicacoes, processos, audiencias e filas do pipeline.",
  },
  {
    id: "advise_sync",
    title: "Sincronizar publicacoes do Advise",
    group: "publicacoes",
    visibility: "ready",
    execution: { kind: "edge_function", functionName: "advise-sync", action: "sync" },
    description: "Busca novas publicacoes no Advise e persiste no Supabase.",
  },
  {
    id: "advise_backfill",
    title: "Rodar backfill do Advise",
    group: "publicacoes",
    visibility: "ready",
    execution: { kind: "edge_function", functionName: "advise-backfill-runner" },
    description: "Processa janelas historicas do backfill de publicacoes.",
  },
  {
    id: "advise_enrich_ai",
    title: "Enriquecer publicacoes com IA",
    group: "ia",
    visibility: "ready",
    execution: { kind: "edge_function", functionName: "advise-ai-enricher" },
    description: "Gera resumo semantico, urgencia e prazo sugerido para publicacoes.",
  },
  {
    id: "recent_publications",
    title: "Listar publicacoes recentes",
    group: "publicacoes",
    visibility: "ready",
    execution: { kind: "workspace_op", operation: "recent_publications" },
    description: "Lista as publicacoes mais recentes com data, CNJ e trecho do conteudo.",
  },
  {
    id: "sync_publicacoes_freshsales",
    title: "Sincronizar publicacoes com Freshsales",
    group: "publicacoes",
    visibility: "ready",
    execution: { kind: "edge_function", functionName: "publicacoes-freshsales", action: "sync" },
    description: "Converte publicacoes em activities e vinculos no CRM.",
  },
  {
    id: "extract_audiencias",
    title: "Extrair audiencias das publicacoes",
    group: "agendamentos",
    visibility: "ready",
    execution: { kind: "edge_function", functionName: "publicacoes-audiencias", action: "extract_batch" },
    description: "Extrai audiencias do texto das publicacoes e grava no Supabase/Freshsales.",
  },
  {
    id: "calcular_prazos",
    title: "Calcular prazos processuais",
    group: "publicacoes",
    visibility: "ready",
    execution: { kind: "edge_function", functionName: "publicacoes-prazos", action: "calcular_lote" },
    description: "Calcula prazos, memorias de contagem e alertas a partir das publicacoes.",
  },
  {
    id: "count_processes",
    title: "Contar processos",
    group: "processos",
    visibility: "ready",
    execution: { kind: "workspace_op", operation: "count_processes" },
    description: "Retorna a quantidade total de processos cadastrados.",
  },
  {
    id: "process_summary_by_cnj",
    title: "Resumir processo por CNJ",
    group: "processos",
    visibility: "ready",
    execution: { kind: "workspace_op", operation: "process_summary_by_cnj" },
    description: "Monta um resumo do processo com publicacoes e prazos pendentes.",
  },
  {
    id: "recent_movements_by_cnj",
    title: "Listar movimentacoes por CNJ",
    group: "processos",
    visibility: "ready",
    execution: { kind: "workspace_op", operation: "recent_movements_by_cnj" },
    description: "Lista os ultimos movimentos de um processo identificado pelo CNJ.",
  },
  {
    id: "datajud_search",
    title: "Consultar DataJud",
    group: "processos",
    visibility: "ready",
    execution: { kind: "edge_function", functionName: "datajud-search" },
    description: "Consulta e persiste dados do processo via DataJud.",
  },
  {
    id: "datajud_worker",
    title: "Processar fila DataJud",
    group: "pipeline",
    visibility: "admin",
    execution: { kind: "edge_function", functionName: "datajud-worker" },
    description: "Processa a fila judicial assicrona e atualiza processo e CRM.",
  },
  {
    id: "processo_sync",
    title: "Sincronizar processos com Freshsales",
    group: "processos",
    visibility: "ready",
    execution: { kind: "edge_function", functionName: "processo-sync", action: "sync_bidirectional" },
    description: "Executa sincronizacao bidirecional entre Supabase e Freshsales.",
  },
  {
    id: "tpu_enrich",
    title: "Enriquecer processo via TPU local",
    group: "processos",
    visibility: "ready",
    execution: { kind: "edge_function", functionName: "tpu-enricher" },
    description: "Enriquece processo com dados locais de parse CNJ e tabelas TPU.",
  },
  {
    id: "contact_lookup",
    title: "Consultar contato no CRM",
    group: "crm",
    visibility: "ready",
    execution: { kind: "workspace_op", operation: "contact_lookup" },
    description: "Busca contato no Freshsales por email e retorna um resumo.",
  },
  {
    id: "account_view",
    title: "Consultar conta no CRM",
    group: "crm",
    visibility: "ready",
    execution: { kind: "workspace_op", operation: "account_view" },
    description: "Visualiza sales account vinculada ao processo ou cliente.",
  },
  {
    id: "appointments_list",
    title: "Listar compromissos",
    group: "agendamentos",
    visibility: "ready",
    execution: { kind: "workspace_op", operation: "appointments_list" },
    description: "Lista compromissos visiveis no Freshsales.",
  },
  {
    id: "schedule_meeting_simple",
    title: "Agendar reuniao simples",
    group: "agendamentos",
    visibility: "ready",
    execution: { kind: "workspace_op", operation: "schedule_meeting_simple" },
    description: "Cria appointment simples no Freshsales a partir de data e horario.",
  },
  {
    id: "fs_contacts_sync",
    title: "Sincronizar contatos Freshsales",
    group: "crm",
    visibility: "admin",
    execution: { kind: "edge_function", functionName: "fs-contacts-sync" },
    description: "Sincroniza contatos entre Supabase e Freshsales.",
  },
  {
    id: "fs_account_repair",
    title: "Corrigir accounts no Freshsales",
    group: "crm",
    visibility: "admin",
    execution: { kind: "edge_function", functionName: "fs-account-repair" },
    description: "Repara campos e sincronizacao de accounts do Freshsales.",
  },
  {
    id: "fs_fix_activities",
    title: "Corrigir activities pendentes",
    group: "crm",
    visibility: "admin",
    execution: { kind: "edge_function", functionName: "fs-fix-activities" },
    description: "Corrige activities inconsistentes ou pendentes no Freshsales.",
  },
  {
    id: "fs_repair_orphans",
    title: "Corrigir campos orfaos",
    group: "crm",
    visibility: "admin",
    execution: { kind: "edge_function", functionName: "fs-repair-orphans", action: "fix_all" },
    description: "Corrige instancia, partes, status e reseta processos presos quando necessario.",
  },
  {
    id: "fs_tag_leilao",
    title: "Aplicar tag de leilao",
    group: "crm",
    visibility: "admin",
    execution: { kind: "edge_function", functionName: "fs-tag-leilao" },
    description: "Marca accounts relacionadas a publicacoes com palavras-chave de leilao.",
  },
  {
    id: "billing_import",
    title: "Importar faturamento para deals",
    group: "financeiro",
    visibility: "admin",
    execution: { kind: "edge_function", functionName: "billing-import" },
    description: "Sincroniza fila de faturamento com deals e recebiveis no Freshsales.",
  },
  {
    id: "freshchat_sync",
    title: "Sincronizar conversas do Freshchat",
    group: "freshchat",
    visibility: "ready",
    execution: { kind: "edge_function", functionName: "fc-ingest-conversations", action: "sync" },
    description: "Ingere conversas do Freshchat no Supabase e na memoria do DotoBot.",
  },
  {
    id: "freshchat_last_conversation",
    title: "Buscar ultima conversa do Freshchat",
    group: "freshchat",
    visibility: "ready",
    execution: { kind: "edge_function", functionName: "fc-last-conversation" },
    description: "Retorna a ultima conversa de um contato no Freshchat.",
  },
  {
    id: "freshchat_update_conversation",
    title: "Atualizar conversa do Freshchat",
    group: "freshchat",
    visibility: "ready",
    execution: { kind: "edge_function", functionName: "fc-update-conversation" },
    description: "Atualiza status, grupo, agente ou prioridade da conversa.",
  },
  {
    id: "freshdesk_queue",
    title: "Listar fila Freshdesk",
    group: "freshdesk",
    visibility: "partial",
    execution: { kind: "workspace_op", operation: "freshdesk_queue" },
    description: "Lista tickets do Freshdesk pela camada do worker, sem Edge Function dedicada no Supabase.",
  },
  {
    id: "ticket_create",
    title: "Abrir ticket de suporte",
    group: "freshdesk",
    visibility: "partial",
    execution: { kind: "workspace_op", operation: "ticket_create" },
    description: "Abre ticket para o cliente via integracao do worker com Freshdesk.",
  },
  {
    id: "conversations_by_email",
    title: "Listar conversas por email",
    group: "agentlab",
    visibility: "ready",
    execution: { kind: "workspace_op", operation: "conversations_by_email" },
    description: "Lista threads historicas registradas para um cliente.",
  },
  {
    id: "slack_notify",
    title: "Enviar notificacao para Slack",
    group: "slack",
    visibility: "admin",
    execution: { kind: "edge_function", functionName: "slack-notify" },
    description: "Publica mensagem em canal Slack com fallback de token.",
  },
  {
    id: "oauth_status",
    title: "Status do OAuth Freshworks",
    group: "oauth",
    visibility: "admin",
    execution: { kind: "edge_function", functionName: "oauth", action: "status" },
    description: "Consulta estado do OAuth do Freshsales/Freshworks.",
  },
  {
    id: "google_calendar_bridge",
    title: "Integracao Google Calendar",
    group: "agendamentos",
    visibility: "partial",
    execution: { kind: "hybrid", module: "functions/lib/agendamento-helpers.js", connector: "codex_apps.google_calendar" },
    description: "Ha helper local e connector rico no ambiente, mas a orquestracao total ainda precisa ser unificada no DotoBot.",
  },
  {
    id: "google_calendar_event_ops",
    title: "Operacoes completas de evento no Google Calendar",
    group: "agendamentos",
    visibility: "ready",
    execution: { kind: "connector", connector: "codex_apps.google_calendar" },
    description: "Lista, busca, cria, atualiza, responde e remove eventos do Google Calendar via connector.",
  },
  {
    id: "google_calendar_availability",
    title: "Disponibilidade no Google Calendar",
    group: "agendamentos",
    visibility: "ready",
    execution: { kind: "connector", connector: "codex_apps.google_calendar" },
    description: "Consulta janelas ocupadas e disponibilidade de calendarios via connector.",
  },
  {
    id: "google_drive_bridge",
    title: "Integracao Google Drive",
    group: "content",
    visibility: "planned",
    execution: { kind: "missing" },
    description: "Nao foi encontrada Edge Function ativa para Google Drive no Supabase HMADV.",
  },
  {
    id: "zoom_meeting_ops",
    title: "Operacoes de reuniao no Zoom",
    group: "agendamentos",
    visibility: "partial",
    execution: { kind: "library_only", module: "functions/lib/zoom-admin.js" },
    description: "A camada local ja cobre token, create, update, get, participants e delete, mas ainda falta surface formal de tools do agente.",
  },
  {
    id: "surveymonkey_bridge",
    title: "Integracao SurveyMonkey",
    group: "content",
    visibility: "planned",
    execution: { kind: "missing" },
    description: "Nao foi encontrada integracao local nem connector disponivel para SurveyMonkey.",
  },
  {
    id: "read_secrets_temp",
    title: "Leitura temporaria de segredos",
    group: "internal",
    visibility: "blocked",
    execution: { kind: "edge_function", functionName: "read-secrets-temp" },
    description: "Ferramenta sensivel; deve permanecer fora do catalogo do DotoBot.",
  },
  {
    id: "get_fs_key",
    title: "Expor chave do Freshsales",
    group: "internal",
    visibility: "blocked",
    execution: { kind: "edge_function", functionName: "get-fs-key" },
    description: "Ferramenta sensivel; nao deve ser exposta ao DotoBot.",
  },
];

export function listDotobotTools(options = {}) {
  const visibility = Array.isArray(options.visibility) && options.visibility.length
    ? new Set(options.visibility)
    : null;
  const group = typeof options.group === "string" ? options.group.trim() : null;

  return DOTOBOT_TOOL_CATALOG.filter((tool) => {
    if (visibility && !visibility.has(tool.visibility)) return false;
    if (group && tool.group !== group) return false;
    return true;
  });
}

export function getDotobotTool(toolId) {
  return DOTOBOT_TOOL_CATALOG.find((tool) => tool.id === toolId) || null;
}

export function listDotobotToolGroups(options = {}) {
  const tools = listDotobotTools(options);
  return [...new Set(tools.map((tool) => tool.group).filter(Boolean))];
}

export function listUserFacingDotobotTools() {
  return listDotobotTools({ visibility: ["ready", "partial", "planned"] });
}
