-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE judiciario.advise_sync_log (
  id bigint NOT NULL DEFAULT nextval('judiciario.advise_sync_log_id_seq'::regclass),
  executado_em timestamp with time zone NOT NULL DEFAULT now(),
  data_inicio date,
  data_fim date,
  total_advise integer DEFAULT 0,
  excluidas_leilao integer DEFAULT 0,
  novas integer DEFAULT 0,
  duplicadas integer DEFAULT 0,
  erros integer DEFAULT 0,
  vinculadas integer DEFAULT 0,
  processos_criados integer DEFAULT 0,
  observacao text,
  CONSTRAINT advise_sync_log_pkey PRIMARY KEY (id)
);
CREATE TABLE judiciario.advise_sync_status (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  fonte text NOT NULL DEFAULT 'ADVISE'::text,
  ultima_data_movimento timestamp with time zone,
  ultima_pagina integer DEFAULT 1,
  total_paginas integer,
  total_registros integer,
  status text DEFAULT 'idle'::text,
  ultima_execucao timestamp with time zone,
  proxima_execucao timestamp with time zone,
  erro text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT advise_sync_status_pkey PRIMARY KEY (id)
);
CREATE TABLE judiciario.datajud_sync_status (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  numero_processo text NOT NULL UNIQUE,
  tribunal text,
  ultima_execucao timestamp with time zone,
  ultimo_search_after jsonb,
  status text,
  erro text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT datajud_sync_status_pkey PRIMARY KEY (id)
);
CREATE TABLE judiciario.endpoints (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome text NOT NULL,
  descricao text,
  categoria text,
  metodo text NOT NULL,
  url text NOT NULL,
  versao text,
  ativo boolean DEFAULT true,
  auth_tipo text NOT NULL,
  auth_header text,
  query_params jsonb,
  path_params jsonb,
  headers jsonb,
  body_schema jsonb,
  response_schema jsonb,
  response_exemplo jsonb,
  rate_limit integer,
  timeout_ms integer DEFAULT 10000,
  base_legal text,
  observacoes text,
  tenant_id uuid,
  criado_por uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT endpoints_pkey PRIMARY KEY (id)
);
CREATE TABLE judiciario.financeiro_processual (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  processo_id uuid,
  data timestamp with time zone NOT NULL,
  descricao text NOT NULL,
  categoria text,
  centro_custo text,
  valor numeric NOT NULL DEFAULT 0,
  situacao text DEFAULT 'A pagar'::text,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT financeiro_processual_pkey PRIMARY KEY (id),
  CONSTRAINT financeiro_processual_processo_id_fkey FOREIGN KEY (processo_id) REFERENCES judiciario.processos(id)
);
CREATE TABLE judiciario.monitoramento_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  processo_id uuid,
  fonte text,
  status text,
  criado_em timestamp with time zone DEFAULT now(),
  prioridade integer DEFAULT 5,
  tentativas integer DEFAULT 0,
  ultimo_erro text,
  executado_em timestamp with time zone,
  proxima_execucao timestamp with time zone,
  payload jsonb,
  tipo text DEFAULT 'publicacao'::text,
  account_id_freshsales text,
  resultado_sync jsonb,
  CONSTRAINT monitoramento_queue_pkey PRIMARY KEY (id),
  CONSTRAINT monitoramento_queue_processo_id_fkey FOREIGN KEY (processo_id) REFERENCES judiciario.processos(id)
);
CREATE TABLE judiciario.movimentacoes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  processo_id uuid,
  data_movimentacao timestamp with time zone,
  conteudo text,
  fonte text DEFAULT 'DATAJUD'::text,
  hash_integridade text UNIQUE,
  freshsales_activity_id text,
  movimento_tpu_id uuid,
  CONSTRAINT movimentacoes_pkey PRIMARY KEY (id),
  CONSTRAINT movimentacoes_processo_id_fkey FOREIGN KEY (processo_id) REFERENCES judiciario.processos(id),
  CONSTRAINT movimentacoes_movimento_tpu_id_fkey FOREIGN KEY (movimento_tpu_id) REFERENCES judiciario.tpu_movimento(id)
);
CREATE TABLE judiciario.movimentos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  processo_id uuid NOT NULL,
  tenant_id uuid,
  codigo integer,
  descricao text,
  data_movimento timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  movimento_tpu_id uuid,
  freshsales_activity_id text,
  CONSTRAINT movimentos_pkey PRIMARY KEY (id),
  CONSTRAINT movimentos_processo_fk FOREIGN KEY (processo_id) REFERENCES judiciario.processos(id),
  CONSTRAINT movimentos_movimento_tpu_id_fkey FOREIGN KEY (movimento_tpu_id) REFERENCES judiciario.tpu_movimento(id)
);
CREATE TABLE judiciario.partes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  processo_id uuid NOT NULL,
  tenant_id uuid,
  nome text,
  tipo text,
  polo text,
  documento text,
  created_at timestamp with time zone DEFAULT now(),
  contact_id_freshsales text,
  tipo_pessoa text,
  advogados jsonb DEFAULT '[]'::jsonb,
  fonte text,
  CONSTRAINT partes_pkey PRIMARY KEY (id),
  CONSTRAINT partes_processo_fk FOREIGN KEY (processo_id) REFERENCES judiciario.processos(id)
);
CREATE TABLE judiciario.processos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  numero_cnj text UNIQUE,
  numero_processo text,
  titulo text,
  classe text,
  assunto text,
  assunto_principal text,
  orgao_julgador text,
  julgador text,
  tribunal text,
  ramo text,
  comarca text,
  grau integer,
  instancia text,
  tipo_acao text,
  tipo_processo_geral text,
  status text,
  status_atual_processo text,
  prioridade text,
  polo_ativo text,
  polo_passivo text,
  outras_partes text,
  valor_causa numeric,
  segredo_justica boolean,
  arquivado boolean,
  data_ajuizamento date,
  data_distribuicao date,
  data_ultima_movimentacao date,
  data_ultimo_movimento date,
  ultimo_movimento_em timestamp with time zone,
  data_ultima_atualizacao_externa timestamp without time zone,
  sistema text,
  area text,
  link_externo_processo text,
  monitorado_escavador boolean DEFAULT false,
  observacoes text,
  cliente_id uuid,
  advogado_responsavel_id uuid,
  escritorio_id uuid,
  created_by_id uuid,
  created_by text,
  is_sample boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp without time zone,
  classe_codigo integer,
  sistema_codigo integer,
  orgao_julgador_codigo integer,
  formato text,
  account_id_freshsales text,
  dados_incompletos boolean DEFAULT false,
  fonte_criacao text,
  classe_id uuid,
  assunto_principal_id uuid,
  assunto_ids ARRAY DEFAULT '{}'::uuid[],
  orgao_julgador_tpu_id uuid,
  parte_representada_adriano text,
  fs_sync_at timestamp with time zone,
  fs_sync_hash text,
  CONSTRAINT processos_pkey PRIMARY KEY (id),
  CONSTRAINT processos_classe_id_fkey FOREIGN KEY (classe_id) REFERENCES judiciario.tpu_classe(id),
  CONSTRAINT processos_assunto_principal_id_fkey FOREIGN KEY (assunto_principal_id) REFERENCES judiciario.tpu_assunto(id),
  CONSTRAINT processos_orgao_julgador_tpu_id_fkey FOREIGN KEY (orgao_julgador_tpu_id) REFERENCES judiciario.tpu_orgao(id)
);
CREATE TABLE judiciario.publicacao_palavras_chave (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  publicacao_id uuid NOT NULL,
  advise_id_publicacao_cliente bigint,
  advise_id bigint,
  advise_id_palavra_chave bigint,
  palavra_chave text,
  tipo_palavra_chave integer,
  CONSTRAINT publicacao_palavras_chave_pkey PRIMARY KEY (id),
  CONSTRAINT fk_publicacao_palavras FOREIGN KEY (publicacao_id) REFERENCES judiciario.publicacoes(id)
);
CREATE TABLE judiciario.publicacao_pastas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  publicacao_id uuid NOT NULL,
  advise_id_pasta bigint,
  nome_pasta text,
  CONSTRAINT publicacao_pastas_pkey PRIMARY KEY (id),
  CONSTRAINT fk_publicacao_pastas FOREIGN KEY (publicacao_id) REFERENCES judiciario.publicacoes(id)
);
CREATE TABLE judiciario.publicacao_processos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  publicacao_id uuid NOT NULL,
  advise_id_publicacao_cliente bigint,
  advise_id_processo bigint,
  numero_processo text,
  numero_cnj text,
  CONSTRAINT publicacao_processos_pkey PRIMARY KEY (id),
  CONSTRAINT fk_publicacao_processos FOREIGN KEY (publicacao_id) REFERENCES judiciario.publicacoes(id)
);
CREATE TABLE judiciario.publicacoes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  processo_id uuid,
  data_publicacao timestamp with time zone,
  conteudo text,
  tem_prazo boolean DEFAULT false,
  prazo_data timestamp with time zone,
  advise_id_publicacao_cliente bigint UNIQUE,
  advise_id_publicacao bigint UNIQUE,
  advise_id_mov_usuario_cliente bigint,
  advise_id_cliente bigint,
  advise_id_usuario_cliente bigint,
  advise_cod_publicacao bigint,
  advise_cod_diario integer,
  advise_cod_caderno integer,
  advise_id_municipio integer,
  advise_id_caderno_diario_edicao bigint,
  data_hora_movimento timestamp with time zone,
  data_hora_cadastro timestamp with time zone,
  ativo boolean,
  ativo_publicacao boolean,
  ano_publicacao integer,
  edicao_diario integer,
  cidade_comarca_descricao text,
  vara_descricao text,
  pagina_inicial_publicacao integer,
  pagina_final_publicacao integer,
  despacho text,
  corrigido boolean,
  lido boolean,
  nome_diario text,
  descricao_diario text,
  nome_caderno_diario text,
  descricao_caderno_diario text,
  nome_cliente text,
  nome_usuario_cliente text,
  numero_processo_api text,
  raw_payload jsonb,
  freshsales_activity_id text,
  freshsales_task_id text,
  adriano_polo text,
  CONSTRAINT publicacoes_pkey PRIMARY KEY (id),
  CONSTRAINT publicacoes_processo_id_fkey FOREIGN KEY (processo_id) REFERENCES judiciario.processos(id)
);
CREATE TABLE judiciario.riscos_processuais (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  processo_id uuid,
  tipo_risco text,
  probabilidade numeric,
  impacto_financeiro numeric,
  analise_ia text,
  CONSTRAINT riscos_processuais_pkey PRIMARY KEY (id),
  CONSTRAINT riscos_processuais_processo_id_fkey FOREIGN KEY (processo_id) REFERENCES judiciario.processos(id)
);
CREATE TABLE judiciario.sync_divergencias (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  processo_id uuid,
  account_id_fs text,
  tipo text NOT NULL,
  campo text,
  valor_supabase text,
  valor_freshsales text,
  resolvido boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT sync_divergencias_pkey PRIMARY KEY (id),
  CONSTRAINT sync_divergencias_processo_id_fkey FOREIGN KEY (processo_id) REFERENCES judiciario.processos(id)
);
CREATE TABLE judiciario.sync_worker_status (
  id integer NOT NULL DEFAULT nextval('judiciario.sync_worker_status_id_seq'::regclass),
  em_execucao boolean DEFAULT false,
  iniciado_em timestamp with time zone,
  ultima_execucao timestamp with time zone,
  ultimo_lote jsonb DEFAULT '{}'::jsonb,
  pendencias jsonb DEFAULT '{}'::jsonb,
  historico jsonb DEFAULT '[]'::jsonb,
  rodadas_atual integer DEFAULT 0,
  erro_ultimo text,
  versao integer DEFAULT 1,
  CONSTRAINT sync_worker_status_pkey PRIMARY KEY (id)
);
CREATE TABLE judiciario.tpu_assunto (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  codigo_cnj integer NOT NULL UNIQUE,
  nome text NOT NULL,
  descricao text,
  area_direito text,
  dispositivo_legal text,
  artigo text,
  sigiloso boolean DEFAULT false,
  assunto_secundario boolean DEFAULT false,
  crime_antecedente boolean DEFAULT false,
  just_estadual boolean DEFAULT false,
  just_federal boolean DEFAULT false,
  just_trabalho boolean DEFAULT false,
  stf boolean DEFAULT false,
  stj boolean DEFAULT false,
  codigo_pai_cnj integer,
  hierarquia_pai_id uuid,
  caminho_hierarquico text,
  ativa boolean DEFAULT true,
  versao_cnj integer,
  importado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT tpu_assunto_pkey PRIMARY KEY (id),
  CONSTRAINT tpu_assunto_hierarquia_pai_id_fkey FOREIGN KEY (hierarquia_pai_id) REFERENCES judiciario.tpu_assunto(id)
);
CREATE TABLE judiciario.tpu_classe (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  codigo_cnj integer NOT NULL UNIQUE,
  nome text NOT NULL,
  sigla text,
  descricao text,
  natureza text,
  polo_ativo text,
  polo_passivo text,
  area_direito text,
  numeracao_propria boolean DEFAULT false,
  just_estadual boolean DEFAULT false,
  just_federal boolean DEFAULT false,
  just_trabalho boolean DEFAULT false,
  just_militar boolean DEFAULT false,
  just_eleitoral boolean DEFAULT false,
  stf boolean DEFAULT false,
  stj boolean DEFAULT false,
  ativa boolean DEFAULT true,
  versao_cnj integer,
  importado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT tpu_classe_pkey PRIMARY KEY (id)
);
CREATE TABLE judiciario.tpu_movimento (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  codigo_cnj integer NOT NULL UNIQUE,
  nome text NOT NULL,
  descricao text,
  tipo text DEFAULT 'outro'::text CHECK (tipo = ANY (ARRAY['despacho'::text, 'decisao'::text, 'sentenca'::text, 'acórdão'::text, 'intimacao'::text, 'citacao'::text, 'outro'::text])),
  gera_prazo boolean DEFAULT false,
  prazo_sugerido_dias integer,
  visibilidade_externa boolean DEFAULT true,
  flg_eletronico boolean DEFAULT false,
  just_estadual boolean DEFAULT false,
  just_federal boolean DEFAULT false,
  just_trabalho boolean DEFAULT false,
  stf boolean DEFAULT false,
  stj boolean DEFAULT false,
  ativa boolean DEFAULT true,
  versao_cnj integer,
  importado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT tpu_movimento_pkey PRIMARY KEY (id)
);
CREATE TABLE judiciario.tpu_orgao (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  codigo_cnj integer NOT NULL UNIQUE,
  nome text NOT NULL,
  tribunal text,
  municipio text,
  uf text,
  grau text,
  especialidade text,
  tipo text,
  juizo_100_digital boolean DEFAULT false,
  ativa boolean DEFAULT true,
  importado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT tpu_orgao_pkey PRIMARY KEY (id)
);
CREATE TABLE judiciario.tpu_sync_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  fonte text NOT NULL,
  tipo_tpu text NOT NULL,
  versao_cnj integer,
  total_registros integer DEFAULT 0,
  inseridos integer DEFAULT 0,
  atualizados integer DEFAULT 0,
  erros integer DEFAULT 0,
  status text DEFAULT 'pendente'::text,
  erro text,
  iniciado_em timestamp with time zone DEFAULT now(),
  concluido_em timestamp with time zone,
  CONSTRAINT tpu_sync_log_pkey PRIMARY KEY (id)
);
